--drop table BIZ.MS_ITEMS ;
--drop table BIZ.MS_SHOPS ;
--drop table BIZ.MS_ORGANIZATION ;


-- INSERT QUERY

	-- BIZ.MS_ORGANIZATION

	INSERT INTO BIZ.MS_ORGANIZATION(ORG_ID_N, ORG_REF_ID_N, NAME_V, DESCRIPTION_V, CREATED_TIME_DT, LAST_UPDATED_TIME_DT, CLOSED_TIME_DT ) VALUES (101,0, 'Enhancesys innovatation pvt.ltd', 'Enhancesys enables transformation of business by protecting and growing revenue, improving operational efficiency and generating savings. Our innovation engines help in creation of new revenue generating service offerings, comprehensive automation and significant performance enhancements.', now() ,now(),NULL);


	-- BIZ.MS_SHOPS

	INSERT INTO BIZ.MS_SHOPS(SHOP_ID_N ,ORG_ID_N, SHOP_TYPE_N, NAME_V, VALUE_V, CREATED_TIME_DT, LAST_UPDATED_TIME_DT, CLOSED_TIME_DT) VALUES (1001, 101, 0, 'Enhancesys innovatation pvt.ltd', '', NOW(),NOW(),NULL);

	-- BIZ.MS_ITEMS

	-- 1001 - Enhancesys Innovations pvt ltd
	INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001001, 1001, 'Shirt', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001002, 1001, 'T-shirt', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001003, 1001, 'Kurta', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001004, 1001, 'Jeans', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001005, 1001, 'Pant', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001006, 1001, 'Pyjama', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001007, 1001, 'Salwaar', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001008, 1001, 'Women-top', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001009, 1001, 'Skirt', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001010, 1001, 'Women-bottom', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001011, 1001, 'Bath towel', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001012, 1001, 'Short', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001013, 1001, 'Tie', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001014, 1001, 'Scarf', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001015, 1001, 'Shawl', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001016, 1001, 'Dupatta', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001017, 1001, 'Blouse', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001018, 1001, 'Blazer', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001019, 1001, 'Sweater', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001020, 1001, 'Waist-coat', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001021, 1001, 'Safari shirt & pant', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001022, 1001, 'Sherwani', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001023, 1001, 'Bedsheet single', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001024, 1001, 'Bedsheet double', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001025, 1001, 'Blanket single', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001026, 1001, 'Blanket double', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001027, 1001, 'Quilt', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001028, 1001, 'Curtain - small', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001029, 1001, 'Curtain - medium', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001030, 1001, 'Curtain - big', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001031, 1001, 'Pets clothes', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001032, 1001, 'Cushion covers', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001033, 1001, 'Pillow covers', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001034, 1001, 'Doormat', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001035, 1001, 'Sofa cover small', '', NOW() );
	INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001036, 1001, 'Sofa cover medium', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001037, 1001, 'Sofa cover large', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001038, 1001, 'Table cloth', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001039, 1001, 'Pillow', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001040, 1001, 'Soft toys small', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001041, 1001, 'Soft toys medium', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001042, 1001, 'Soft toys large', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001043, 1001, 'Car seat cover', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001044, 1001, 'Carpet', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001045, 1001, 'Kids wear', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001046, 1001, 'Saree silk', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001047, 1001, 'Saree cotton', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001048, 1001, 'Saree light-designer', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001049, 1001, 'Saree medium-designer', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001050, 1001, 'Saree heavy-designer', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001051, 1001, 'Wedding dress', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001052, 1001, 'Kameez', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001053, 1001, 'Heavy kameez', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001054, 1001, 'Dress - short', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001055, 1001, 'Dress long', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001056, 1001, 'Nighty', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001057, 1001, 'Frock', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001058, 1001, 'Gown', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001059, 1001, 'Sharara', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001060, 1001, 'Anarkali suit - light', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001061, 1001, 'Anarkali suit - medium', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001062, 1001, 'Anarkali suit - heavy', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001063, 1001, 'Lehenga set', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001064, 1001, 'Overcoat', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001065, 1001, 'Jacket', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001066, 1001, 'Pullover', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001067, 1001, 'Sweater', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001068, 1001, 'Socks', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001069, 1001, 'Inner wear', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001070, 1001, 'Handkerchief', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001071, 1001, 'Dhoti - single', '', NOW() );
    INSERT INTO BIZ.MS_ITEMS (ITEM_ID_N, SHOP_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1001072, 1001, 'Dhoti - double', '', NOW() );
    
	
	
	