
-- 1168 QURO_STATUS column added
update interface.ms_interface_attr set value_v = 'DATE|MICRO|SITE_ID|ID_OUTLET|QTY|AMOUNT|QSSO_STATUS|ERRORCODE|ERRORMESSAGE' where attribute_id_n = 1168027;
update interface.ms_interface_attr set value_v = 'DATE|MICRO|SITE_ID|ID_OUTLET|QTY|AMOUNT|QSSO_STATUS' where attribute_id_n = 1168031;
update interface.ms_interface_attr set value_v = 'DATE;M;D;yyyyMMdd%MICRO;M;R;%SITE_ID;M;R;%ID_OUTLET;M;R;%QTY;M;R;[0-9]*+%AMOUNT;M;R;^-?([0-9]\d*(\.\d{1,2}+)?)$%QSSO_STATUS;M;R;[0-1]+' where attribute_id_n = 1168032;
update interface.ms_interface_attr set value_v = '{"process_enabled":true,"fields":{"actor_field":{"10":"ID_OUTLET","12":"SITE_ID"},"metric_field":"","source_field":"MICRO","instance_field":"QSSO_STATUS"},"error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"},"pre_aggregation_conf":{"1":"monthly","2":"daily"},"lookup_query":"","notexist-lookup-flag":true,"table_name":"tr_temp_daily_sso_aggr","daily_table":"tr_daily_daily_sso_aggr","monthly_table":"tr_monthly_daily_sso_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":2,"no_of_monthly_join_queries":2,"duplicate_validation_conf":{"schema_name":"kpi","table_name":"tr_validate_daily_sso_aggr","field_indexes":[0,1,2,3,6],"include-fileId":true},"data_filter":[]}' where attribute_id_n = 1168037;

-- 1181 QSSO_STATUS column added
update interface.ms_interface_attr set value_v = 'DATE|MICRO|SITE_ID|OUTLET|HIT|AMOUNT|QURO_STATUS|ERRORCODE|ERRORMESSAGE' where attribute_id_n = 1181027;
update interface.ms_interface_attr set value_v = 'DATE|MICRO|SITE_ID|OUTLET|HIT|AMOUNT|QURO_STATUS' where attribute_id_n = 1181031;
update interface.ms_interface_attr set value_v = 'DATE;M;RD;[0-9]*;yyyyMMdd%MICRO;M;R;%SITE_ID;M;R;%OUTLET;M;R;%HIT;M;R;[0-9]+%AMOUNT;M;R;^-?([0-9]\d*(\.\d{1,2}+)?)$%QURO_STATUS;M;R;[0-1]+' where attribute_id_n = 1181032;
update interface.ms_interface_attr set value_v = '{"process_enabled":true,"fields":{"actor_field":{"10":"OUTLET","12":"SITE_ID"},"metric_field":"","source_field":"MICRO","instance_field":"QURO_STATUS"},"error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"},"pre_aggregation_conf":{"1":"monthly","2":"daily"},"table_name":"tr_temp_uro_20k_aggr","lookup_query":"","notexist-lookup-flag":true,"daily_table":"tr_daily_uro_20k_aggr","monthly_table":"tr_monthly_uro_20k_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":2,"no_of_monthly_join_queries":2,"data_filter":[],"duplicate_validation_conf":{"schema_name":"kpi","table_name":"tr_validate_uro_20k_aggr","include-fileId":true,"field_indexes":[0,1,2,3,6]}}' where attribute_id_n = 1181037;
