-- 1153
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153037, 1153, 'Field Lookup Conf', '{"process_enabled":true,"fields":{"actor_field":"ORGANIZATION_ID","metric_field":"","source_field":"MPC_CODE","instance_field":""},"error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"},"table_name":"tr_temp_secondary_mobo_aggr","lookup_query":"","notexist_lookup":"","no_of_params":{},"daily_table":"tr_daily_secondary_mobo_aggr","monthly_table":"tr_monthly_secondary_mobo_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1}', now());


--1165
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1165037, 1165, 'Field Lookup Conf', '{"process_enabled":true,"fields":{"actor_field":"ID OUTLET","metric_field":"","source_field":"SITE ID","instance_field":""},"error_codes":{"actor_field":"60101","metric_field":"","source_field":"60301","instance_field":""},"table_name":"tr_temp_mobii_rguga_injection_aggr","lookup_query":"","notexist_lookup":"","no_of_params":{},"daily_table":"tr_daily_mobii_rguga_injection_aggr","monthly_table":"tr_monthly_mobii_rguga_injection_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1,"data_filter":[{"field_index":4,"values":["YES","yes","Yes","true","True","TRUE"],"operation":"in"}]}', now());


--1166
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1166037, 1166, 'Field Lookup Conf', '{"process_enabled":true,"fields":{"actor_field":"ID_OUTLET","metric_field":"","source_field":"SITE_ID","instance_field":""},"error_codes":{"actor_field":"60101","metric_field":"","source_field":"60301","instance_field":""},"table_name":"tr_temp_mobii_daily_sso_aggr","lookup_query":"","notexist_lookup":"","no_of_params":{},"daily_table":"tr_daily_mobii_daily_sso_aggr","monthly_table":"tr_monthly_mobii_daily_sso_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1}', now());
