-- Integration Sequence Scripts

--CREATE DATABASE SNOC2;
DROP SCHEMA IF EXISTS JOBENGINE CASCADE;
DROP SCHEMA IF EXISTS JOBENGINE_AUD CASCADE;
CREATE SCHEMA JOBENGINE;
CREATE SCHEMA JOBENGINE_AUD;

CREATE SEQUENCE JOBENGINE.HIBERNATE_SEQUENCE INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.TR_JOBENGINE_FILE_SUM_DET_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.TR_JOBENGINE_FILE_SUM_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.TR_JOBENGINE_FAILURE_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.TR_JOBENGINE_SUMMARY_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.MS_ADDR_VERIFICATION_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

CREATE SEQUENCE JOBENGINE.MS_JOBENGINE_NOTIFICATION_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

