-- 1048 

-- Remote 1
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.251' WHERE ATTRIBUTE_ID_N = 1048034;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1048035;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1048036;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1048037;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/' WHERE ATTRIBUTE_ID_N = 1048038;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/' WHERE ATTRIBUTE_ID_N = 1048039;
-- Remote 2
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.143' WHERE ATTRIBUTE_ID_N = 1048041;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1048042;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1048043;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1048044;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/' WHERE ATTRIBUTE_ID_N = 1048045;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/' WHERE ATTRIBUTE_ID_N = 1048046;

-- 1057

-- Remote 1
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.251' WHERE ATTRIBUTE_ID_N = 1057034;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1057035;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1057036;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1057037;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/' WHERE ATTRIBUTE_ID_N = 1057038;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/' WHERE ATTRIBUTE_ID_N = 1057039;
-- Remote 2
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.143' WHERE ATTRIBUTE_ID_N = 1057041;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1057042;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1057043;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1057044;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/' WHERE ATTRIBUTE_ID_N = 1057045;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/' WHERE ATTRIBUTE_ID_N = 1057046;


-- 1058

-- Remote 1
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.251' WHERE ATTRIBUTE_ID_N = 1058034;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1058035;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1058036;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1058037;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/' WHERE ATTRIBUTE_ID_N = 1058038;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/' WHERE ATTRIBUTE_ID_N = 1058039;
-- Remote 2
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.143' WHERE ATTRIBUTE_ID_N = 1058041;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1058042;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1058043;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1058044;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/' WHERE ATTRIBUTE_ID_N = 1058045;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/' WHERE ATTRIBUTE_ID_N = 1058046;


-- 1059

-- Remote 1
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.251' WHERE ATTRIBUTE_ID_N = 1059034;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1059035;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1059036;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1059037;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/' WHERE ATTRIBUTE_ID_N = 1059038;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/' WHERE ATTRIBUTE_ID_N = 1059039;
-- Remote 2
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '192.168.2.143' WHERE ATTRIBUTE_ID_N = 1059041;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '22' WHERE ATTRIBUTE_ID_N = 1059042;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'appuser' WHERE ATTRIBUTE_ID_N = 1059043;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = 'app@123' WHERE ATTRIBUTE_ID_N = 1059044;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/' WHERE ATTRIBUTE_ID_N = 1059045;
UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/' WHERE ATTRIBUTE_ID_N = 1059046;




--------------------------------------- INSERT ----------------------------------------------------------------------------------

INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048032, 1048, 'Remote Servers', 'Remote Server1, Remote Server2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048033, 1048, 'Remote Server1', 'Remote Host1, Remote Port1, Remote User1, Remote Password1, Remote Dir1, Remote control directory1, Send Control File Flag1', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048034, 1048, 'Remote Host1', '192.168.2.251', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048035, 1048, 'Remote Port1', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048036, 1048, 'Remote User1', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048037, 1048, 'Remote Password1', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048038, 1048, 'Remote Dir1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048039, 1048, 'Remote control directory1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048040, 1048, 'Remote Server2', 'Remote Host2, Remote Port2, Remote User2, Remote Password2, Remote Dir2, Remote control directory2, Send Control File Flag2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048041, 1048, 'Remote Host2', '192.168.2.143', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048042, 1048, 'Remote Port2', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048043, 1048, 'Remote User2', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048044, 1048, 'Remote Password2', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048045, 1048, 'Remote Dir2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048046, 1048, 'Remote control directory2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/activation_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048047, 1048, 'Send Control File Flag1', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1048048, 1048, 'Send Control File Flag2', 'true', now());

INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057032, 1057, 'Remote Servers', 'Remote Server1, Remote Server2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057033, 1057, 'Remote Server1', 'Remote Host1, Remote Port1, Remote User1, Remote Password1, Remote Dir1, Remote control directory1, Send Control File Flag1', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057034, 1057, 'Remote Host1', '192.168.2.251', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057035, 1057, 'Remote Port1', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057036, 1057, 'Remote User1', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057037, 1057, 'Remote Password1', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057038, 1057, 'Remote Dir1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057039, 1057, 'Remote control directory1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057040, 1057, 'Remote Server2', 'Remote Host2, Remote Port2, Remote User2, Remote Password2, Remote Dir2, Remote control directory2, Send Control File Flag2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057041, 1057, 'Remote Host2', '192.168.2.143', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057042, 1057, 'Remote Port2', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057043, 1057, 'Remote User2', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057044, 1057, 'Remote Password2', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057045, 1057, 'Remote Dir2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057046, 1057, 'Remote control directory2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_detail_dist/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057047, 1057, 'Send Control File Flag1', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1057048, 1057, 'Send Control File Flag2', 'true', now());

INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058032, 1058, 'Remote Servers', 'Remote Server1, Remote Server2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058033, 1058, 'Remote Server1', 'Remote Host1, Remote Port1, Remote User1, Remote Password1, Remote Dir1, Remote control directory1, Send Control File Flag1', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058034, 1058, 'Remote Host1', '192.168.2.251', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058035, 1058, 'Remote Port1', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058036, 1058, 'Remote User1', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058037, 1058, 'Remote Password1', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058038, 1058, 'Remote Dir1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058039, 1058, 'Remote control directory1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058040, 1058, 'Remote Server2', 'Remote Host2, Remote Port2, Remote User2, Remote Password2, Remote Dir2, Remote control directory2, Send Control File Flag2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058041, 1058, 'Remote Host2', '192.168.2.143', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058042, 1058, 'Remote Port2', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058043, 1058, 'Remote User2', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058044, 1058, 'Remote Password2', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058045, 1058, 'Remote Dir2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058046, 1058, 'Remote control directory2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_injected/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058047, 1058, 'Send Control File Flag1', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1058048, 1058, 'Send Control File Flag2', 'true', now());

INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059032, 1059, 'Remote Servers', 'Remote Server1, Remote Server2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059033, 1059, 'Remote Server1', 'Remote Host1, Remote Port1, Remote User1, Remote Password1, Remote Dir1, Remote control directory1, Send Control File Flag1', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059034, 1059, 'Remote Host1', '192.168.2.251', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059035, 1059, 'Remote Port1', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059036, 1059, 'Remote User1', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059037, 1059, 'Remote Password1', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059038, 1059, 'Remote Dir1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059039, 1059, 'Remote control directory1', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059040, 1059, 'Remote Server2', 'Remote Host2, Remote Port2, Remote User2, Remote Password2, Remote Dir2, Remote control directory2, Send Control File Flag2', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059041, 1059, 'Remote Host2', '192.168.2.143', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059042, 1059, 'Remote Port2', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059043, 1059, 'Remote User2', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059044, 1059, 'Remote Password2', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059045, 1059, 'Remote Dir2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059046, 1059, 'Remote control directory2', '/home/appuser/interfaces/DAILY_DUMPS/master_files/vc_data_redeem_detail/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059047, 1059, 'Send Control File Flag1', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1059048, 1059, 'Send Control File Flag2', 'true', now());

