DELETE FROM INTERFACE.MS_INTERFACE_ATTR WHERE INTERFACE_ID_N = 1153;
DELETE FROM INTERFACE.MS_INTERFACE WHERE INTERFACE_ID_N = 1153;
DELETE FROM INTERFACE.MS_MODULE WHERE MODULE_ID_N = 232;

-- MS_MODULE
INSERT INTO INTERFACE.MS_MODULE(MODULE_ID_N, NAME_V, CALL_BACK_V, LAST_UPDATED_TIME_DT, DESCRIPTION_V) VALUES (232, 'INTDW024 - Secondary MOBO', NULL , NOW(), 'Incoming Secondary MOBO File from DWH');

-- MS_INTERFACE
INSERT INTO INTERFACE.MS_INTERFACE (INTERFACE_ID_N, NAME_V, MODULE_ID_N, INTERFACE_TYPE_N, TRANS_TYPE_N, SEQ_N, CONVERTER_V, PUBLISHER_V, RESPONSE_PROCESSOR_V, LAST_UPDATED_TIME_DT) VALUES (1153, 'INTDW027 - MOBII RGU-GA Injection', 232, 2, 2, 1, 'java:global/EnhancesysManagement/IntegrationServices/CSVtoJSONConverter!com.enhancesys.integration.services.interfaces.converter.DataConverter', 'java:global/EnhancesysManagement/IntegrationPublishers/WebServicePublisher!com.enhancesys.integration.services.interfaces.publisher.DataPublisher', NULL, NOW());

-- Attributes for interface 1153 (INTDW024 - Secondary MOBO - Receive file)

INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153001, 1153, 'Remote Host', 'REMOTE_HOST', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153002, 1153, 'Remote Port', 'REMOTE_PORT', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153003, 1153, 'Remote User', 'REMOTE_USER', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153004, 1153, 'Remote Password', 'REMOTE_PWD', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153005, 1153, 'Remote File', 'secondary_mobo_bi', now());                                 
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153006, 1153, 'Remote FileName Format', 'yyyyMMdd', now());                    
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153007, 1153, 'Remote File Format', 'csv', now());                                   
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153008, 1153, 'Control file format', 'ctl', now());                                  
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153009, 1153, 'Remote Dir', '/home/appuser/interfaces/DWH/master_files/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153010, 1153, 'Remote control directory', '/home/appuser/interfaces/DWH/master_files/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153011, 1153, 'Remote rejected directory', '/home/appuser/interfaces/DWH/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153012, 1153, 'Remote rejected control directory', '/home/appuser/interfaces/DWH/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153013, 1153, 'Remote backup directory', '/home/appuser/interfaces/DWH/backup/master_files/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153014, 1153, 'Remote Control Backup Directory', '/home/appuser/interfaces/DWH/backup/master_files/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153015, 1153, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153016, 1153, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153017, 1153, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153018, 1153, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153019, 1153, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153020, 1153, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153021, 1153, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153022, 1153, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153023, 1153, 'Local Filter Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/filter_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153024, 1153, 'Local Filter Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/filter_file/secondary_mobo/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153025, 1153, 'Received File Type', 'Request File Type', now());                     
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153026, 1153, 'Csv Delimeter', '\|', now());                                         
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153027, 1153, 'Rejection File Headers', 'MPC_CODE|DATE|ORGANIZATION_ID|DEALER_MSISDN|AMOUNT|ERRORCODE|ERRORMESSAGE', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153028, 1153, 'Rejection File Preparation Class', 'java:global/EnhancesysManagement/IntegrationServices/DWHRejectionFilePreparation!com.enhancesys.integration.services.interfaces.rejection.RejectionFilePreparation', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153029, 1153, 'Client Id', '0', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153030, 1153, 'Is Sftp', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153031, 1153, 'File Headers', 'MPC_CODE|DATE|ORGANIZATION_ID|DEALER_MSISDN|AMOUNT', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153032, 1153, 'Field Validation Conf', 'MPC_CODE;M;R;[a-zA-Z0-9]+%DATE;M;D;yyyy-MM-dd%ORGANIZATION_ID;M;R;[a-zA-Z0-9]+%DEALER_MSISDN;N;R;[0-9]+%AMOUNT;M;R;^-?([0-9]\d*(\.\d+)?)$', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153033, 1153, 'CSV MERGER', 'java:global/EnhancesysManagement/IntegrationServices/GenericFileProcessor!com.enhancesys.integration.services.interfaces.merger.CSVMerger', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153034, 1153, 'Validation Conf Delimiter', '%', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153035, 1153, 'File Data Batch Size', '5000', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153036, 1153, 'Rejection File Query', 'select data_string_v, error_code, error_message from kpi.tr_temp_upload_aggr_failure where file_id_n = ?', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153037, 1153, 'Field Lookup Conf', '{"process_enabled":true,"fields":{"actor_field":"ORGANIZATION_ID","metric_field":"","source_field":"MPC_CODE","instance_field":""},"error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"},"table_name":"tr_temp_secondary_mobo_aggr","lookup_query":"","notexist_lookup":"","no_of_params":{},"daily_table":"tr_daily_secondary_mobo_aggr","monthly_table":"tr_monthly_secondary_mobo_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1,"duplicate_validation_conf":{"field_indexes":[0,1,2],"schema_name":"kpi","table_name":"tr_temp_secondary_mobo_validation"}}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153038, 1153, 'Incoming File Records Limit', '', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153039, 1153, 'PPK Path', '/home/appuser/snoc/snocconf/interfaceconf/credentials/TEST_251.ppk', NOW());




--Email Notification Attributes for interface -->INTDW024 - Secondary MOBO
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153001, 1153, 'FILE_REJECTED_CTL_0', 'email', 'int_md5_hash_key_failed', 'FILE REJECTED - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153002, 1153, 'FILE_NOT_FOUND_0', 'email', 'int_file_not_found', 'FILE NOT FOUND - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153003, 1153, 'FILE_REJECTED_PART_0', 'email', 'int_file_rejected_partially', 'FILE REJECTED PARTIALLY - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153004, 1153, 'FILE_REJECTED_FULL_0', 'email', 'int_file_rejected_fully', 'FILE REJECTED FULLY - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153005, 1153, 'FILE_SUCCESS_0', 'email', 'int_file_processed_sucessfully', 'FILE SUCCESSFULLY PROCESSED - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 2, now(),'en');
INSERT INTO INTERFACE.MS_INTERFACE_NOTIFICATION (INTERFACE_NOTIFICATION_ID_N, INTERFACE_ID_N, SCENARIO_V, MEDIA_V, TEMPLATE_NAME_V, SUBJECT_V, TO_FIRST_NAME_V, TO_ADDRESS_V, TO_CC_V, TO_BCC_V, STATUS_N, LAST_UPDATED_TIME_DT,LANGUAGE_V) VALUES (1153006, 1153, 'CONNECTION_REFUSED_0', 'email', 'int_connection_refused', 'CONNECTION REFUSED - INTSM017 - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
