-- SCEAMA : BIZ
		drop table BIZ.MS_ITEMS ;
		drop table BIZ.MS_SHOPS ;
		drop table BIZ.MS_ORGANIZATION ;
      -- TABLE VM_ORG
      CREATE TABLE BIZ.MS_ORGANIZATION
      (
      	ORG_ID_N			    	NUMERIC(19, 0) NOT NULL,
      	ORG_REF_ID_N				NUMERIC(19, 0) NOT NULL,
      	NAME_V						CHARACTER VARYING(75) NOT NULL,
      	DESCRIPTION_V				CHARACTER VARYING(3000),
      	CREATED_TIME_DT				TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      	CLOSED_TIME_DT				TIMESTAMP WITH TIME ZONE DEFAULT NULL,
      	CONSTRAINT VM_ORG_PKEY PRIMARY KEY(ORG_ID_N)
      );
      
      
      
      -- TABLE VM_ORG_SHOP
      CREATE TABLE BIZ.MS_SHOPS
      (
      	SHOP_ID_N				    NUMERIC(19, 0) NOT NULL,
      	ORG_ID_N					NUMERIC(19, 0) NOT NULL,
      	SHOP_TYPE_N				    NUMERIC(19, 0) NOT NULL,
      	NAME_V						CHARACTER VARYING(255) NOT NULL,	
      	VALUE_V						CHARACTER VARYING(2550) NOT NULL,	
      	CREATED_TIME_DT				TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      	CLOSED_TIME_DT				TIMESTAMP WITH TIME ZONE DEFAULT NULL,
      	
      	CONSTRAINT VM_ORG_SHOPS_PKEY PRIMARY KEY(SHOP_ID_N),
      	CONSTRAINT VM_ORG_SHOPS_FKEY FOREIGN KEY(ORG_ID_N) REFERENCES BIZ.MS_ORGANIZATION(ORG_ID_N)
      );
            
      
      -- TABLE VM_ORG_SHOP_ATTR
      CREATE TABLE BIZ.MS_ITEMS
      (
      	ITEM_ID_N				    NUMERIC(19, 0) NOT NULL,
      	SHOP_ID_N				    NUMERIC(19, 0) NOT NULL,
      	NAME_V						CHARACTER VARYING(75) NOT NULL,	
      	VALUE_V						CHARACTER VARYING(2550) NOT NULL,	
      	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
      	
      	CONSTRAINT MS_ITEMS_PKEY PRIMARY KEY(ITEM_ID_N),
      	CONSTRAINT MS_ITEMS_FKEY FOREIGN KEY(SHOP_ID_N) REFERENCES BIZ.MS_SHOPS(SHOP_ID_N)
      );
      