INSERT INTO INTERFACE.MS_MODULE(MODULE_ID_N, NAME_V, CALL_BACK_V, DESCRIPTION_V) VALUES  (227, 'DAILY_DUMP - Attendance Details', null , '');

INSERT INTO INTERFACE.MS_INTERFACE (INTERFACE_ID_N, NAME_V, MODULE_ID_N, INTERFACE_TYPE_N, TRANS_TYPE_N, SEQ_N, CONVERTER_V, PUBLISHER_V, RESPONSE_PROCESSOR_V, LAST_UPDATED_TIME_DT) VALUES (1145, 'DAILY_DUMP - Master Hierarchy Feed', 227, 2, 1, 1, 'java:global/EnhancesysManagement/IntegrationServices/GenericDailyDump!com.enhancesys.integration.services.interfaces.processor.PullFromMongo', '', NULL, now());








--Attributes for interface 1145 (DAILY_DUMP - Master Hierarchy Feed)
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145001, 1145, 'Remote Host', 'REMOTE_HOST', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145002, 1145, 'Remote Port', 'REMOTE_PORT', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145003, 1145, 'Remote User', 'REMOTE_USER', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145004, 1145, 'Remote Password', 'REMOTE_PWD', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145005, 1145, 'Remote File', 'master_hierarchy_feed', now());                                                                             
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145006, 1145, 'Remote FileName Format', 'yyyyMMdd', now());                                                                          
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145007, 1145, 'Remote File Format', 'csv', now());                                                                                         
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145008, 1145, 'Control file format', 'ctl', now());                                                                                        
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145009, 1145, 'Remote Dir', '/home/appuser/interfaces/DAILY_DUMPS/master_files/master_hierarchy_feed/', now());                 
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145010, 1145, 'Remote control directory', '/home/appuser/interfaces/DAILY_DUMPS/master_files/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145011, 1145, 'Remote rejected directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145012, 1145, 'Remote rejected control directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145013, 1145, 'Remote backup directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145014, 1145, 'Remote Control Backup Directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145015, 1145, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145016, 1145, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145017, 1145, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145018, 1145, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145019, 1145, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145020, 1145, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145021, 1145, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145022, 1145, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/master_hierarchy_feed/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145023, 1145, 'Received File Type', 'Request File Type', now());                                                                           
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145024, 1145, 'Csv Delimeter', '|', now());                                                                                               
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145025, 1145, 'File Headers', 'Region Name|HOR Name|HOR Mobile Number|Sub Area Name|HOS Name|HOS Mobile Number|Sales Area Name|SAM Name|SAM Mobile Number|Cluster Name|MPC Name|MPC Mobile Number|Micro Cluster Name|CSM Name|CSM Mobile Number|Supervisor Code|Supervisor Mobile Number|CSO Code|CSO Mobile Number|Outlet Code|Outlet Name|Outlet Mobile Number|Outlet_category|Channel|Outlet_business_type|Outlet_Class|beat_name|Beat ID|MOBO Dealer', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145026, 1145, 'Client Id', '0', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145027, 1145, 'Is Sftp', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145028, 1145, 'Schema Name', 'daily_dump', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145029, 1145, 'Collection Name', 'outlet_hierachy_dump', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145030, 1145, 'Daily Dump Conf', '{"region name":"region_name","hor name":"hor_name","hor mobile number":"hor_mobile_number","sub area name":"sub_area_name","hos name":"hos_name","hos mobile number":"hos_mobile_number","sales area name":"sales_area_name","sam name":"sam_name","sam mobile number":"sam_mobile_number","cluster name":"cluster_name","mpc name":"mpc_name","mpc mobile number":"mpc_mobile_number","micro cluster name":"micro_cluster_name","csm name":"csm_name","csm mobile number":"csm_mobile_number","supervisor code":"supervisor_code","supervisor mobile number":"supervisor_mobile_number","cso code":"cso_code","cso mobile number":"cso_mobile_number","outlet code":"outlet_code","outlet name":"outlet_name","outlet mobile number":"outlet_mobile_number","outlet_category":"outlet_category","channel":"channel","outlet_business_type":"outlet_business_type","outlet_class":"outlet_class","beat_name":"beat_name","beat id":"beat_id","mobo dealer":"mobo_dealer"}', now());
-- INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1145031, 1145, 'Query Field', 'dump_crtd_dt_num', now());
