
-- MS_MODULE
INSERT INTO INTERFACE.MS_MODULE(MODULE_ID_N, NAME_V, CALL_BACK_V, DESCRIPTION_V) VALUES  (262, 'DAILY_DUMP - Stock_Reorder_Dump', null , '');

-- MS_INTERFACE
INSERT INTO INTERFACE.MS_INTERFACE (INTERFACE_ID_N, NAME_V, MODULE_ID_N, INTERFACE_TYPE_N, TRANS_TYPE_N, SEQ_N, CONVERTER_V, PUBLISHER_V, RESPONSE_PROCESSOR_V, LAST_UPDATED_TIME_DT) VALUES (1184, 'DAILY_DUMP - Stock_Reorder_Dump', 262, 2, 1, 1, 'java:global/EnhancesysManagement/IntegrationServices/GenericDailyDump!com.enhancesys.integration.services.interfaces.processor.PullFromMongo', '', NULL, now());

-- MS_INTERFACE_ATTR
--1184 (Stock_Reorder_Dump)
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184001, 1184, 'Remote Host', 'REMOTE_HOST', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184002, 1184, 'Remote Port', 'REMOTE_PORT', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184003, 1184, 'Remote User', 'REMOTE_USER', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184004, 1184, 'Remote Password', 'REMOTE_PWD', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184005, 1184, 'Remote File', 'Stock_Reorder_Dump', now());                                                                             
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184006, 1184, 'Remote FileName Format', 'yyyyMMdd', now());                                                                          
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184007, 1184, 'Remote File Format', 'csv', now());                                                                                         
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184008, 1184, 'Control file format', 'ctl', now());                                                                                        
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184009, 1184, 'Remote Dir', '/home/appuser/interfaces/DAILY_DUMPS/master_files/stock_reorder/', now());                 
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184010, 1184, 'Remote control directory', '/home/appuser/interfaces/DAILY_DUMPS/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184011, 1184, 'Remote rejected directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184012, 1184, 'Remote rejected control directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184013, 1184, 'Remote backup directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184014, 1184, 'Remote Control Backup Directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184015, 1184, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184016, 1184, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184017, 1184, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184018, 1184, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184019, 1184, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184020, 1184, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184021, 1184, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184022, 1184, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184023, 1184, 'Received File Type', 'Request File Type', now());                                                                           
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184024, 1184, 'Csv Delimeter', '|', now());                                                                                               
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184025, 1184, 'File Headers', 'CHANNEL_CATEGORY|REGIONAL|AREA|SALES_AREA|CLUSTER|MICRO_CLUSTER|SALE_TERRITORY|TERRITORY_ID|OUTLET_ID|OUTLET_REF_CODE|OUTLET_NAME|CSO_NAME|CSO_OPERATOR_ID|CSO_ORG_ID|CSO_ORG_REF_CODE|CSO_ORG_NAME|PRODUCT_CATEGORY_ID|PRODUCT_CATEGORY_NAME|THRESHOLD_VALUE|AVAILABLE_STOCK|STOCK_DAYS|STOCK_PERCENTAGE|PREV_MONTH_SALES|PREV_MONTH_SALES_VALUE|PREV_MONTH_TRANSACTION_DAYS|INCREASE_BY_PERCENTAGE|PREV_DAY_SELL-IN|PREV_DAY_SUGGESTION|REMAINING_SUGGESTION|ACTUAL_SUGGESTION|TODAY_PJP', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184026, 1184, 'Client Id', '0', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184027, 1184, 'Is Sftp', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184028, 1184, 'Daily Dump Conf', '{"channel_category":"","regional":"","area":"","sales_area":"","cluster":"","micro_cluster":"","sale_territory":"","territory_id":"","outlet_id":"","outlet_ref_code":"","outlet_name":"","cso_name":"","cso_operator_id":"","cso_org_id":"","cso_org_ref_code":"","cso_org_name":"","product_category_id":"","product_category_name":"","threshold_value":"","available_stock":"","stock_days":"","stock_percentage":"","prev_month_sales":"","prev_month_sales_value":"","prev_month_transaction_days":"","increase_by_percentage":"","prev_day_sell-in":"","prev_day_suggestion":"","remaining_suggestion":"","actual_suggestion":"","today_pjp":""}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184029, 1184, 'query', 'select ''1184_Detail_Package_Activation_A'' as report_name, report_day_master.date_v as date, null as channel, report_network_master.region_v as region, report_network_master.area_v as area, report_network_master.sales_area_v as salesarea, report_network_master.cluster_v as cluster, report_network_master.micro_cluster_v as microcluster, null as additionalterritory, report_network_master.territory_code_v as territoryid, report_network_master.lac_id_v as lacid, report_network_master.cell_id_v as cellid, system_source.metrics_name_v as systemsource, null as sid, null as smstext, metrics_master.ext_reference_id_v as packagecode, metrics_master.metrics_name_v as packagename, groupby_query_results.activation_qty as qty, groupby_query_results.activation_value as amount from (select daily_upload_metrics_aggr.day_id_n as day_id_n, daily_upload_metrics_aggr.actor_id_n as actor_id_n, daily_upload_metrics_aggr.metrics_id_n as metrics_id_n, daily_upload_metrics_aggr.instance_id_n as instance_id_n, round(sum((daily_upload_metrics_aggr.dimension_1_n)/100),2) as activation_qty, round(sum((daily_upload_metrics_aggr.dimension_2_n)/100),2) as activation_value from kpi.tr_daily_package_act_seller_aggr as daily_upload_metrics_aggr where daily_upload_metrics_aggr.day_id_n = (select to_number(to_char(date(now() - interval ''1 day''),''yyyymmdd''),''99999999'')) and daily_upload_metrics_aggr.metrics_type_n in (13) group by daily_upload_metrics_aggr.day_id_n, daily_upload_metrics_aggr.actor_id_n, daily_upload_metrics_aggr.metrics_id_n, daily_upload_metrics_aggr.instance_id_n order by day_id_n desc ) as groupby_query_results inner join kpi.ms_report_network_master as report_network_master on (groupby_query_results.actor_id_n = report_network_master.aggregation_id_n) inner join kpi.ms_metrics_master as system_source on (groupby_query_results.instance_id_n = system_source.metrics_id_n) inner join kpi.ms_metrics_master as metrics_master on (groupby_query_results.metrics_id_n = metrics_master.metrics_id_n) inner join kpi.ms_report_day_master as report_day_master on (groupby_query_results.day_id_n = report_day_master.day_id_n)', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184030, 1184, 'PPK Path', '/home/appuser/snoc/snocconf/interfaceconf/credentials/TEST_251.ppk', NOW());

