--1184 (Stock_Reorder_Dump)

--delete from interface.ms_interface_attr where interface_id_n = 1184;
--delete from interface.ms_interface where interface_id_n = 1184;
--delete from interface.ms_module where module_id_n = 262;

-- MS_MODULE
INSERT INTO INTERFACE.MS_MODULE(MODULE_ID_N, NAME_V, CALL_BACK_V, DESCRIPTION_V) VALUES  (262, 'DAILY_DUMP - Stock_Reorder_Dump', null , '');

-- MS_INTERFACE
INSERT INTO INTERFACE.MS_INTERFACE (INTERFACE_ID_N, NAME_V, MODULE_ID_N, INTERFACE_TYPE_N, TRANS_TYPE_N, SEQ_N, CONVERTER_V, PUBLISHER_V, RESPONSE_PROCESSOR_V, LAST_UPDATED_TIME_DT) VALUES (1184, 'DAILY_DUMP - Stock_Reorder_Dump', 262, 2, 1, 1, 'java:global/EnhancesysManagement/IntegrationServices/GenericDailyDump!com.enhancesys.integration.services.interfaces.processor.PullFromMongo', '', NULL, now());

-- MS_INTERFACE_ATTR
--Attributes for interface 1184 (DAILY_DUMP - Stock_Reorder_Dump)
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184001, 1184, 'Remote Host', 'REMOTE_HOST', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184002, 1184, 'Remote Port', 'REMOTE_PORT', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184003, 1184, 'Remote User', 'REMOTE_USER', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184004, 1184, 'Remote Password', 'REMOTE_PWD', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184005, 1184, 'Remote File', 'Stock_Reorder_Dump', now());                                                                             
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184006, 1184, 'Remote FileName Format', 'yyyyMMdd', now());                                                                          
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184007, 1184, 'Remote File Format', 'csv', now());                                                                                         
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184008, 1184, 'Control file format', 'ctl', now());                                                                                        
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184009, 1184, 'Remote Dir', '/home/appuser/interfaces/DAILY_DUMPS/master_files/stock_reorder/', now());                 
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184010, 1184, 'Remote control directory', '/home/appuser/interfaces/DAILY_DUMPS/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184011, 1184, 'Remote rejected directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184012, 1184, 'Remote rejected control directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184013, 1184, 'Remote backup directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184014, 1184, 'Remote Control Backup Directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184015, 1184, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184016, 1184, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184017, 1184, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184018, 1184, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184019, 1184, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184020, 1184, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184021, 1184, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184022, 1184, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/stock_reorder/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184023, 1184, 'Received File Type', 'Request File Type', now());                                                                           
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184024, 1184, 'Csv Delimeter', '|', now());                                                                                               
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184025, 1184, 'File Headers', 'CHANNEL_CATEGORY|REGIONAL|AREA|SALES_AREA|CLUSTER|MICRO_CLUSTER|SALE_TERRITORY|TERRITORY_ID|OUTLET_ID|OUTLET_REF_CODE|OUTLET_NAME|CSO_NAME|CSO_OPERATOR_ID|CSO_ORG_ID|CSO_ORG_REF_CODE|CSO_ORG_NAME|PRODUCT_CATEGORY_ID|PRODUCT_CATEGORY_NAME|THRESHOLD_VALUE|AVAILABLE_STOCK|STOCK_DAYS|STOCK_PERCENTAGE|PREV_MONTH_SALES|PREV_MONTH_SALES_VALUE|PREV_MONTH_TRANSACTION_DAYS|INCREASE_BY_PERCENTAGE|PREV_DAY_SELL-IN|PREV_DAY_SUGGESTION|REMAINING_SUGGESTION|ACTUAL_SUGGESTION|TODAY_PJP', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184026, 1184, 'Client Id', '0', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184027, 1184, 'Is Sftp', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184028, 1184, 'Daily Dump Conf', '{"channel_category":"channel_category","regional":"regional","area":"area","sales_area":"sale_sarea","cluster":"cluster","micro_cluster":"micro_cluster","sale_territory":"sale_territory","territory_id":"territory_id","outlet_id":"outlet_id","outlet_ref_code":"outlet_ref_code","outlet_name":"outlet_name","cso_name":"cso_name","cso_operator_id":"cso_operator_id","cso_org_id":"cso_org_id","cso_org_ref_code":"cso_org_ref_code","cso_org_name":"cso_org_name","product_category_id":"product_category_id","product_category_name":"product_category_name","threshold_value":"threshold_value","available_stock":"available_stock","stock_days":"stock_days","stock_percentage":"stock_percentage","prev_month_sales":"prev_month_sales","prev_month_sales_value":"prev_month_sales_value","prev_month_transaction_days":"prev_month_transaction_days","increase_by_percentage":"increase_by_percentage","prev_day_sell-in":"prev_day_sellin","prev_day_suggestion":"prev_day_suggestion","remaining_suggestion":"remaining_suggestion","actual_suggestion":"actual_suggestion","today_pjp":"today_pjp"}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184029, 1184, 'query', 'select channel_category_v as channel_category, regional_v as regional, area_v as area, sales_area_v as sale_sarea, cluster_v as cluster, micro_cluster_v as micro_cluster, sale_territory_v as sale_territory, territory_id_v as territory_id, org_id_n as outlet_id, outlet_ref_code_v as outlet_ref_code, outlet_name_v as outlet_name, cso_name_v as cso_name, cso_operator_id_v as cso_operator_id, cso_org_id_n as cso_org_id, cso_org_ref_code_v as cso_org_ref_code, cso_org_name_v as cso_org_name, prd_ctgr_id_n as product_category_id, prd_ctgr_name_v as product_category_name, threshold_n as threshold_value, stock_value_n as available_stock, stock_days_n as stock_days, percentage_n as stock_percentage, sales_flag_bl as prev_month_sales, prev_month_sales_n as prev_month_sales_value, transaction_days_n as prev_month_transaction_days, inc_by_percent_n as increase_by_percentage, prev_sellin_n as prev_day_sellin, prev_suggestion_n as prev_day_suggestion, rem_suggestion_n as remaining_suggestion, actual_suggestion_n as actual_suggestion, pjp_status_v as today_pjp from kpi.tr_stock_reorder_aggr where day_id_n = ( select to_char(( select date ''yesterday''), ''yyyymmdd'')::numeric ) union select channel_category_v as channel_category, regional_v as regional, area_v as area, sales_area_v as sale_sarea, cluster_v as cluster, micro_cluster_v as micro_cluster, sale_territory_v as sale_territory, territory_id_v as territory_id, org_id_n as outlet_id, outlet_ref_code_v as outlet_ref_code, outlet_name_v as outlet_name, cso_name_v as cso_name, cso_operator_id_v as cso_operator_id, cso_org_id_n as cso_org_id, cso_org_ref_code_v as cso_org_ref_code, cso_org_name_v as cso_org_name, prd_ctgr_id_n as product_category_id, prd_ctgr_name_v as product_category_name, threshold_n as threshold_value, stock_value_n as available_stock, stock_days_n as stock_days, percentage_n as stock_percentage, sales_flag_bl as prev_month_sales, prev_month_sales_n as prev_month_sales_value, transaction_days_n as prev_month_transaction_days, inc_by_percent_n as increase_by_percentage, prev_sellin_n as prev_day_sellin, prev_suggestion_n as prev_day_suggestion, rem_suggestion_n as remaining_suggestion, actual_suggestion_n as actual_suggestion, pjp_status_v as today_pjp from kpi.tr_stock_suggest_aggr where day_id_n = ( select to_char(( select date ''yesterday''), ''yyyymmdd'')::numeric ) ;', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1184030, 1184, 'PPK Path', '/home/appuser/snoc/snocconf/interfaceconf/credentials/TEST_251.ppk', NOW());

