--  select * from interface.ms_interface_attr where interface_id_n = 1061 and name_v ilike '%FETCH%' order by 1;
--	ATTRIBUTE_ID_N|INTERFACEID|KEYS
	
--	1061027|1061|FETCH_QUERIES
--	FETCH_QUERY1,FETCH_QUERY2,FETCH_QUERY3,FETCH_QUERY4,FETCH_QUERY5,FETCH_QUERY6
	
--	1061028|1061|FETCH_QUERY1
	select partner_org_master.org_id_n::text as partnerorgid, partner_org_master.ref_code_v as partnerexternalref , partner_org_master.node_id_n::text as partnernodeid, partner_org_master.node_name_v as partnernodename,metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid,day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),0) as closingstock ,coalesce(sum(daily_partner_stock.quantity_n),0) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partner_org_master on (day_master.date_dt between ? and ? and partner_org_master.org_type_n !=6 and org_id_n not in (1,2039) ) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) inner join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and partner_org_master.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) inner join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and partner_org_master.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref , partnernodeid, partnernodename, productid, externalproductid, date order by partnerorgid, partnernodeid, partnernodename, date;
	
--	1061029|1061|FETCH_QUERY2
	select * from ( select partner_org_master.org_id_n::text as partnerorgid,partner_org_master.ref_code_v as partnerexternalref , partner_org_master.node_id_n::text as partnernodeid, partner_org_master.node_name_v as partnernodename,metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid,day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),0) as closingstock ,coalesce(sum(daily_partner_stock.quantity_n),null) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partner_org_master on (day_master.date_dt between ? and ? and partner_org_master.org_type_n !=6 and org_id_n not in (1,2039) ) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) inner join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and partner_org_master.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) left join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and partner_org_master.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref , partnernodeid, partnernodename, productid, externalproductid, date order by partnerorgid, partnernodeid, partnernodename, date ) as dummy where partnerclosingstock is null;
	
--	1061030|1061|FETCH_QUERY3
	select * from ( select partner_org_master.org_id_n::text as partnerorgid,partner_org_master.ref_code_v as partnerexternalref , partner_org_master.node_id_n::text as partnernodeid, partner_org_master.node_name_v as partnernodename,metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid,day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),null) as closingstock ,coalesce(sum(daily_partner_stock.quantity_n),0) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partner_org_master on (day_master.date_dt between ? and ? and partner_org_master.org_type_n !=6 and org_id_n not in (1,2039) ) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) left join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and partner_org_master.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) inner join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and partner_org_master.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref, partnernodeid, partnernodename, productid, externalproductid, date order by partnerorgid, partnernodeid, partnernodename, date ) as dummy where closingstock is null ;
	
--	1061032|1061|FETCH_QUERY4
	select posOrg.parent_org_id_n::text as partnerorgid, partnerOrg.ref_code_v as partnerexternalref , posOrg.node_id_n::text as partnernodeid, metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid, day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),0) as closingstock, coalesce(sum(daily_partner_stock.quantity_n),0) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partnerOrg on (day_master.date_dt between ? and ? and partnerOrg.org_type_n in(11)) inner join kpi.ms_org_master as posOrg on ( partnerOrg.org_id_n=posOrg.parent_org_id_n) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) inner join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and posOrg.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) inner join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and posOrg.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref , partnernodeid, productid, externalproductid, date order by partnerorgid, partnernodeid, date;
	
--	1061033|1061|FETCH_QUERY5
  	select * from ( select posOrg.parent_org_id_n::text as partnerorgid, partnerOrg.ref_code_v as partnerexternalref , posOrg.node_id_n::text as partnernodeid, metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid, day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),0) as closingstock, coalesce(sum(daily_partner_stock.quantity_n),null) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partnerOrg on (day_master.date_dt between ? and ? and partnerOrg.org_type_n in(11)) inner join kpi.ms_org_master as posOrg on ( partnerOrg.org_id_n=posOrg.parent_org_id_n) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) inner join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and posOrg.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) left join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and posOrg.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref , partnernodeid, productid, externalproductid, date order by partnerorgid, partnernodeid, date ) as dummy where partnerclosingstock is null ;
	
--	1061034|1061|FETCH_QUERY6
  	select * from ( select posOrg.parent_org_id_n::text as partnerorgid, partnerOrg.ref_code_v as partnerexternalref , posOrg.node_id_n::text as partnernodeid, metrics_mapping.ext_entity_id_v as productid, product.sku_code_v as externalproductid, day_master.date_dt as date, coalesce(sum(daily_stock.opening_stock_qty_n),0) as openingstock, coalesce(sum(daily_stock.stock_in_qty_n),0) as stockin, coalesce(sum(daily_stock.stock_out_qty_n),0) as stockout, coalesce(sum(daily_stock.closing_stock_qty_n),null) as closingstock, coalesce(sum(daily_partner_stock.quantity_n),0) as partnerclosingstock from kpi.ms_day_master as day_master inner join kpi.ms_org_master as partnerOrg on (day_master.date_dt between ? and ? and partnerOrg.org_type_n in(11)) inner join kpi.ms_org_master as posOrg on ( partnerOrg.org_id_n=posOrg.parent_org_id_n) inner join kpi.ms_metrics_master as product on (product.metrics_type_n = 13) inner join kpi.mp_metrics_mapping as metrics_mapping on (product.metrics_id_n = metrics_mapping.metrics_id_n) inner join interface.tr_daily_partner_stock_balance as daily_partner_stock on (day_master.date_dt = daily_partner_stock.date_dt and posOrg.node_id_n = daily_partner_stock.unique_entity_id_n and metrics_mapping.ext_entity_id_v = daily_partner_stock.product_code_v) inner join kpi.tr_daily_stock_ledger as daily_stock on (daily_stock.metrics_org_id_n = 2039 and day_master.day_id_n = daily_stock.day_id_n and posOrg.node_id_n = daily_stock.node_id_n and product.metrics_id_n = daily_stock.metrics_id_n) where (daily_stock.day_id_n is not null and daily_partner_stock.date_dt is not null) or daily_stock.opening_stock_qty_n > 0 or daily_stock.stock_in_qty_n > 0 or daily_stock.stock_out_qty_n > 0 or daily_stock.closing_stock_qty_n > 0 or daily_partner_stock.quantity_n > 0 group by partnerorgid, partnerexternalref , partnernodeid, productid, externalproductid, date order by partnerorgid, partnernodeid, date ) as dummy where closingstock is null ;

