-- Need to have an EntityMapping for the orderType and functionId for snoc related items..

CREATE TABLE JOBENGINE.REVISION_HISTORY
(
	ID				INTEGER NOT NULL,
	"TIMESTAMP"		BIGINT NOT NULL,
	USERNAME		CHARACTER VARYING(255),
	CONSTRAINT REVISION_HISTORY_ID_PKEY PRIMARY KEY (ID )
);

CREATE TABLE JOBENGINE.REV_CHANGES
(
	REV				INTEGER NOT NULL,
	ENTITY_NAME_V	CHARACTER VARYING(255),
	CONSTRAINT REV_CHANGES_REC_FKEY FOREIGN KEY (REV) REFERENCES JOBENGINE.REVISION_HISTORY (ID) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.SD_TENANT
(
	TENANT_ID_N				NUMERIC(19,0) NOT NULL, -- A unique id to represent the each tenant
	NAME_V					CHARACTER VARYING(255) NOT NULL, -- The name of the Subsidiary.
	START_DATE_DT			TIMESTAMP WITH TIME ZONE NOT NULL, -- The period for which the tenant is applicable from the date
	END_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL, -- The period for which the tenant is applicable till the date
	LAST_UPDATED_TIME_DT	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT SD_TENANT_TENANT_ID_N_PKEY PRIMARY KEY (TENANT_ID_N ),
	CONSTRAINT TENANT_MAST_NAME_UNQ1 UNIQUE (NAME_V )
);

CREATE TABLE JOBENGINE.SD_STATUS
(
	STATUS_N				NUMERIC(19,0) NOT NULL, -- A unique id to represent the each status
	NAME_V					CHARACTER VARYING(255), -- Represent the Status
	TENANT_ID_N				NUMERIC(19,0) NOT NULL, -- Tenant which avails this status
	START_DATE_DT			TIMESTAMP WITH TIME ZONE NOT NULL, --  The period for which the status is applicable from the date
	END_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL, -- The period for which the status is applicable till the date
	LAST_UPDATED_TIME_DT	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT SD_STATUS_STATUS_N_PKEY PRIMARY KEY (STATUS_N ),
	CONSTRAINT SD_STATUS_TENANT_ID_N_FKEY FOREIGN KEY (TENANT_ID_N) REFERENCES JOBENGINE.SD_TENANT (TENANT_ID_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT STATUS_MAST_NAME_UNQ1 UNIQUE (NAME_V )
);

CREATE TABLE JOBENGINE.SD_APPLICATION
(
	APPLICATION_ID_N			NUMERIC(19,0) NOT NULL,
	APPLICATION_NAME_V			CHARACTER VARYING(255) NOT NULL,
	START_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL,
	END_DATE_DT					TIMESTAMP WITH TIME ZONE NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT SD_APPLICATION_PKEY PRIMARY KEY (APPLICATION_ID_N ),
	CONSTRAINT APPLICATION_NAME_UNQ1 UNIQUE (APPLICATION_NAME_V )
);

CREATE TABLE JOBENGINE.SD_ENTITY_TYPE
(
	ENTITY_TYPE_N				NUMERIC(19,0) NOT NULL,
	NAME_V						CHARACTER VARYING(255),
	START_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL,
	END_DATE_DT					TIMESTAMP WITH TIME ZONE NOT NULL,
	TENANT_ID_N					NUMERIC(19,0) NOT NULL,
	STATUS_N					NUMERIC(19,0),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT SD_ENTITY_TYPE_PKEY PRIMARY KEY (ENTITY_TYPE_N ),
	CONSTRAINT SD_ENTITY_TYPE_STATUS_N_FKEY FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT SD_ENTITY_TYPE_TENANT_ID_N_FKEY FOREIGN KEY (TENANT_ID_N) REFERENCES JOBENGINE.SD_TENANT (TENANT_ID_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.SD_LOOKUP_TYPE
(
	LOOKUP_TYPE_N				NUMERIC(19,0) NOT NULL,
	NAME_V						CHARACTER VARYING(255),
	START_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL,
	END_DATE_DT					TIMESTAMP WITH TIME ZONE NOT NULL,
	TENANT_ID_N					NUMERIC(19,0) NOT NULL,
	STATUS_N					NUMERIC(19,0),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT SD_LOOKUP_TYPE_PKEY PRIMARY KEY (LOOKUP_TYPE_N ),
	CONSTRAINT SD_LOOKUP_TYPE_STATUS_N_FKEY FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT SD_LOOKUP_TYPE_TENANT_ID_N_FKEY FOREIGN KEY (TENANT_ID_N) REFERENCES JOBENGINE.SD_TENANT (TENANT_ID_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.MS_LOOKUP
(
	LOOKUP_ID_N					NUMERIC(19,0) NOT NULL,
	LOOKUP_TYPE_N				NUMERIC(19,0),
	NAME_V						CHARACTER VARYING(255) NOT NULL,
	SHORT_NAME_V				CHARACTER VARYING(100),
	RELATED_LOOKUP_TYPE_N		NUMERIC(19,0),
	RELATED_LOOKUP_ID_N			NUMERIC(19,0),
	START_DATE_DT				TIMESTAMP WITH TIME ZONE NOT NULL,
	END_DATE_DT					TIMESTAMP WITH TIME ZONE NOT NULL,
	STATUS_N					NUMERIC(19,0) NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT MS_LOOKUP_PKEY PRIMARY KEY (LOOKUP_ID_N ),
	CONSTRAINT MS_LOOKUP_LOOKUP_TYPE_N_FKEY FOREIGN KEY (LOOKUP_TYPE_N) REFERENCES JOBENGINE.SD_LOOKUP_TYPE (LOOKUP_TYPE_N) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT MS_LOOKUP_RELATED_LOOKUP_TYPE_N_FKEY FOREIGN KEY (RELATED_LOOKUP_TYPE_N) REFERENCES JOBENGINE.SD_LOOKUP_TYPE (LOOKUP_TYPE_N) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT MS_LOOKUP_STATUS_N_FKEY FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.TR_ENTITY_MAPPING
(
	MAPPING_ID_N				NUMERIC(19,0) NOT NULL,
	ENTITY_TYPE_N				NUMERIC(19,0) NOT NULL,
	ENTITY_ID_N					NUMERIC(19,0),
	APPLICATION_ID_N			NUMERIC(19,0),
	ID_1_V						CHARACTER VARYING(255) NOT NULL,
	ID_2_V						CHARACTER VARYING(40),
	ID_3_V						CHARACTER VARYING(40),
	DESCRIPTION_V				CHARACTER VARYING(255),
	FIELD_1_V					CHARACTER VARYING(255),
	FIELD_2_V					CHARACTER VARYING(255),
	FIELD_3_V					CHARACTER VARYING(255),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_ENTITY_MAPPING_PKEY PRIMARY KEY (MAPPING_ID_N ),
	CONSTRAINT TR_ENTITY_MAPPING_APPLICATION_ID_FKEY FOREIGN KEY (APPLICATION_ID_N) REFERENCES JOBENGINE.SD_APPLICATION (APPLICATION_ID_N) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT TR_ENTITY_MAPPING_ENTITY_TYPE_FKEY FOREIGN KEY (ENTITY_TYPE_N) REFERENCES JOBENGINE.SD_ENTITY_TYPE (ENTITY_TYPE_N) MATCH SIMPLE
		ON UPDATE NO ACTION ON DELETE NO ACTION
);

--One module per application..
-- ASYNC_QUEUE_MODULE_TYPE = 1
-- ASYNC_FILE_MODULE_TYPE = 2
-- SYNC_MODULE_TYPE = 3
-- SEND_TRANS_TYPE = 1
-- RECEIVE_TRANS_TYPE = 2
CREATE TABLE JOBENGINE.MS_MODULE
(
	MODULE_ID_N					NUMERIC(19, 0) NOT NULL,
	NAME_V						CHARACTER VARYING(255) NOT NULL,		-- ApplicationName
	MODULE_TYPE_N				NUMERIC(19, 0) NOT NULL,			-- Sync/Async(File/Queue)
	TRANS_TYPE_N				NUMERIC(19, 0) NOT NULL,			-- send/receive
	SEQ_N						NUMERIC(19, 0),
	CONVERTER_V					CHARACTER VARYING(500) NOT NULL,
	PUBLISHER_V					CHARACTER VARYING(500) NOT NULL,
	RESPONSE_PROCESSOR_V		CHARACTER VARYING(500),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT MS_MODULE_PKEY   PRIMARY KEY(MODULE_ID_N)
);

--Publisher/Converter/ResponseConsumers moved to the attributes..
CREATE TABLE JOBENGINE.MS_MODULE_ATTR
(
	ATTRIBUTE_ID_N				NUMERIC(19, 0) NOT NULL,
	MODULE_ID_N					NUMERIC(19, 0) NOT NULL,
	NAME_V						CHARACTER VARYING(255) NOT NULL,
	VALUE_V						CHARACTER VARYING(5000) NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT MS_MODULE_ATTR_PKEY PRIMARY KEY(ATTRIBUTE_ID_N),
	CONSTRAINT MS_MODULE_ATTR_FKEY FOREIGN KEY(MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N)
);

-- OUT_FILE_TYPE = 1
-- IN_FILE_TYPE = 2
CREATE TABLE JOBENGINE.TR_MODULE_SUMMARY
(
	TRANS_ID_N					NUMERIC(19,0) NOT NULL,
	MODULE_ID_N					NUMERIC(19,0) NOT NULL,
	ORGNL_REQUEST_DATA_B		OID NOT NULL,
	REQUEST_DATA_B				OID NOT NULL,
	REQUEST_TIME_DT				TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	DUE_TIME_DT					TIMESTAMP WITHOUT TIME ZONE,
	ACK_DATA_B					OID,
	ACK_TIME_DT					TIMESTAMP WITHOUT TIME ZONE,
	ORGNL_RESPONSE_DATA_B		OID,
	RESPONSE_DATA_B				OID,
	RESPONSE_TIME_DT			TIMESTAMP WITHOUT TIME ZONE,
	STATUS_N					NUMERIC(19,0) NOT NULL,
	RETRY_COUNT_N				NUMERIC(19,0),
	REF_DATA1_V					CHARACTER VARYING(255),
	REF_DATA2_N					NUMERIC(19,0),
	REF_DATA3_N					NUMERIC(19,0),
	REF_DATA4_N					NUMERIC(19,0),
	REF_DATA5_V					CHARACTER VARYING(255),
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_MODULE_SUMMARY_PKEY PRIMARY KEY (TRANS_ID_N ),
	CONSTRAINT TR_MODULE_SUMMARY_FKEY FOREIGN KEY (MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT TR_MODULE_SUMMARY_STATUS_FKEY FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.TR_MODULE_FILE_SUMMARY
(
	FILE_ID_N				NUMERIC(19,0) NOT NULL,
	FILE_NAME_V				CHARACTER VARYING(255) NOT NULL,
	MODULE_ID_N				NUMERIC(19,0) NOT NULL,
	RECEIVED_SERVER_V		CHARACTER VARYING(1000),
	SEND_SERVER_V			CHARACTER VARYING(2000),
	LOCAL_SERVER_V			CHARACTER VARYING(2000),
	TOTAL_COUNT_N			NUMERIC(19,0) NOT NULL,
	SUCCESS_COUNT_N			NUMERIC(19,0),
	ERROR_COUNT_N			NUMERIC(19,0),
	FILTER_COUNT_N			NUMERIC(19,0),
	UPLOADED_BY_N			NUMERIC(19,0),
	STATUS_N				NUMERIC(19,0) NOT NULL,
	MESSAGE_V				CHARACTER VARYING(1000),
	ERROR_MESSAGE_V			CHARACTER VARYING(1000),
	RETRY_COUNT_N       	NUMERIC(2) DEFAULT 0,
	VALIDATED_ON_DT			TIMESTAMP WITH TIME ZONE,
	PROCESSED_ON_DT			TIMESTAMP WITH TIME ZONE,
	UPLOADED_ON_DT			TIMESTAMP WITH TIME ZONE,
	LAST_UPDATED_TIME_DT	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_MODULE_FILE_SUMMARY_PKEY PRIMARY KEY (FILE_ID_N ),
	CONSTRAINT TR_INTRFC_FILE_SUM_FKEY FOREIGN KEY(MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N),
	CONSTRAINT TR_INTRFC_FILE_SUM_STATUS_FKEY FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N)
);

CREATE TABLE JOBENGINE.TR_MODULE_FAILURE
(
	TRANS_FAILURE_ID_N		NUMERIC(19,0) NOT NULL,
	TRANS_ID_N				NUMERIC(19,0) NOT NULL,
	ACK_DATA_B				OID,
	ACK_TIME_DT				TIMESTAMP WITHOUT TIME ZONE,
	RESPONSE_DATA_B			OID,
	RESPONSE_TIME_DT		TIMESTAMP WITHOUT TIME ZONE,
	ERROR_CODE_N			NUMERIC(19,0) NOT NULL,
	ERROR_MESSAGE_V			CHARACTER VARYING(4000) NOT NULL,
	FILE_ID_N				NUMERIC(19,0),
	LAST_UPDATED_TIME_DT	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_MODULE_FAILURE_PKEY PRIMARY KEY (TRANS_FAILURE_ID_N ),
	CONSTRAINT TR_MODULE_FAILURE_FKEY FOREIGN KEY (TRANS_ID_N) REFERENCES JOBENGINE.TR_MODULE_SUMMARY (TRANS_ID_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.TR_MODULE_FILE_SUMMARY_DETAILS
(
	FILE_DETAILS_ID_N		NUMERIC(19,0) NOT NULL,
	FILE_ID_N				NUMERIC(19,0) NOT NULL,
	FILE_NAME_V				CHARACTER VARYING(500) NOT NULL,
	CTRL_FILE_NAME_V		CHARACTER VARYING(500) NOT NULL,
	FILE_TYPE_V				CHARACTER VARYING(1) NOT NULL,			-- A(Actual)/R(Rejected)
	TOTAL_COUNT_N			NUMERIC(19,0),
	SUCCESS_COUNT_N			NUMERIC(19,0),
	ERROR_COUNT_N			NUMERIC(19,0),
	LAST_UPDATED_TIME_DT	TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_MODULE_FILE_SUMMARY_DETAILS_PKEY PRIMARY KEY (FILE_DETAILS_ID_N ),
	CONSTRAINT TR_INTRFC_FILE_SUM_DET_FKEY FOREIGN KEY (FILE_ID_N) REFERENCES JOBENGINE.TR_MODULE_FILE_SUMMARY (FILE_ID_N) MATCH SIMPLE 
		ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.MS_MODULE_NOTIFICATION
(
	MODULE_NOTIFICATION_ID_N		NUMERIC(19,0) NOT NULL, -- A unique id to represent the each notification
	MODULE_ID_N						NUMERIC(19,0) NOT NULL,
	SCENARIO_V						CHARACTER VARYING(255) NOT NULL, -- The name of the Subsidiary (like File_Not_Avail, File_Rejected, Rejection_File_Transferred).
	MEDIA_V							CHARACTER VARYING(20) NOT NULL,-- email or sms
	TEMPLATE_NAME_V					CHARACTER VARYING(255) NOT NULL,-- should be same as mongodb template id which is in genericMasterValueCollection with transitionTypeId as  811
	SUBJECT_V						CHARACTER VARYING(255) NOT NULL,
	TO_FIRST_NAME_V					CHARACTER VARYING(255) NOT NULL,
	TO_ADDRESS_V					CHARACTER VARYING(500) NOT NULL,--to whom need to send email, if it is multiple give comma seperated value
	TO_CC_V							CHARACTER VARYING(500),
	TO_BCC_V						CHARACTER VARYING(500),
	STATUS_N						NUMERIC(19,0) NOT NULL,
	LANGUAGE_V						CHARACTER VARYING(255),
	LAST_UPDATED_TIME_DT			TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT INTRFC_NOTIFICATION_ID_N_PKEY PRIMARY KEY (MODULE_NOTIFICATION_ID_N ),
	CONSTRAINT INTRFC_NOTIFICATION_INT_ID_FK FOREIGN KEY (MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N) MATCH SIMPLE 
		ON UPDATE NO ACTION ON DELETE NO ACTION,
	CONSTRAINT INTRFC_NOTIFICATION_SCENRIO_V UNIQUE (MODULE_ID_N, SCENARIO_V, MEDIA_V),
	CONSTRAINT INTRFC_STATUS_ID_FK FOREIGN KEY (STATUS_N) REFERENCES JOBENGINE.SD_STATUS (STATUS_N) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE JOBENGINE.MS_ADDR_VERIFICATION
(
	ADDR_VERIFICATION_ID_N			NUMERIC(19,0) NOT NULL,
	TO_ADDRESS_V					CHARACTER VARYING(500) NOT NULL,
	IS_VERIFIED						BOOLEAN NOT NULL,
	IS_VERFIY_LINK_SENT				BOOLEAN,
	VERFIY_LINK_SENT_DATE_DT		TIMESTAMP WITH TIME ZONE,
	LAST_UPDATED_TIME_DT TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT ADDR_VERFICATION_ID_N_PK PRIMARY KEY (ADDR_VERIFICATION_ID_N)
);

CREATE TABLE JOBENGINE.MS_BOUNCED_EMAIL
(
	BOUNCE_ID_N					SERIAL PRIMARY KEY,
	BOUNCE_MAIL_ID_V			CHARACTER VARYING(500) NOT NULL,
	BOUNCE_TYPE_V				CHARACTER VARYING(200) NOT NULL,
	BOUNCE_SUB_TYPE_V			CHARACTER VARYING(200) NOT NULL,
	ACTION_V					CHARACTER VARYING(200) NOT NULL,
	DIAGNOSTIC_CODE_V			CHARACTER VARYING(500) NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

--CREATE OR REPLACE FUNCTION JOBENGINE.module_data_cleanup(days integer)
--  RETURNS VOID AS $body$
--DECLARE
--    dayscnt int := days;
--BEGIN
--    delete from JOBENGINE.tr_module_failure where trans_id_n in (select trans_id_n from JOBENGINE.tr_module_summary  where ref_data3_n in (select file_id_n from JOBENGINE.tr_module_file_summary where last_updated_time_dt < current_date - dayscnt));
--	delete from JOBENGINE.tr_module_summary  where ref_data3_n in (select file_id_n from JOBENGINE.tr_module_file_summary where last_updated_time_dt < current_date - dayscnt);
--	delete from JOBENGINE.tr_module_file_summary_details  where file_id_n in (select file_id_n from JOBENGINE.tr_module_file_summary where last_updated_time_dt < current_date - dayscnt);
--	delete from JOBENGINE.tr_module_file_summary where last_updated_time_dt < current_date - dayscnt;
--	delete from JOBENGINE.tr_module_failure where trans_id_n in (select trans_id_n from JOBENGINE.tr_module_summary where last_updated_time_dt < current_date - dayscnt and ref_data3_n is NULL);
--	delete from JOBENGINE.tr_module_summary where last_updated_time_dt < current_date - dayscnt and ref_data3_n is NULL;
--END;
--$body$LANGUAGE PLPGSQL;

--Index creation 
CREATE INDEX DUPTRCHECK_INDEX ON JOBENGINE.TR_MODULE_SUMMARY (REF_DATA1_V,REF_DATA5_V,STATUS_N,REF_DATA2_N);

CREATE TABLE JOBENGINE.TR_DAILY_DUMP_SUMMARY
(
	DUMP_ID_N					NUMERIC(19,0) NOT NULL,
	MODULE_ID_N					NUMERIC(19,0) NOT NULL,
	CREATED_DATE_DT				DATE NOT NULL,
	STATUS_N					NUMERIC(19,0) NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_DAILY_DUMP_SUMMARY_PK PRIMARY KEY (DUMP_ID_N),
	CONSTRAINT TR_DAILY_DUMP_SUMMARY_FK FOREIGN KEY(MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N),
	CONSTRAINT TR_DAILY_DUMP_SUMMARY_UK UNIQUE (MODULE_ID_N, CREATED_DATE_DT)
);

-- KYC_FLAG : 
-- 0 = DISABLE
-- 1 = ENABLE
CREATE TABLE JOBENGINE.MS_KYC_SYNC_INFO
(
	SYNC_ID_N					NUMERIC(19,0) NOT NULL,
	MODULE_ID_N					NUMERIC(19,0) NOT NULL,
	KYC_FIELD_V					CHARACTER VARYING(255) NOT NULL,
	KYC_FLAG_N					NUMERIC(1) NOT NULL DEFAULT 1,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT MS_KYC_SYNC_INFO_PK PRIMARY KEY (SYNC_ID_N),
	CONSTRAINT MS_KYC_SYNC_INFO_FK FOREIGN KEY(MODULE_ID_N) REFERENCES JOBENGINE.MS_MODULE (MODULE_ID_N)
);