-- CSO DUMP QUERIES:
--(1) SSO:
select cso_org_links.node_id_n as node_id_n, count(distinct(outlet_org_master.org_id_n)) as sso_outlets_n from (select distinct(source_id_n) as source_id_n from kpi.tr_daily_serial_injection_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 11 and actor_type_n = 2 ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.source_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by cso_org_links.node_id_n order by cso_org_links.node_id_n;

--(2) SSO 3+:
select cso_org_links.node_id_n as node_id_n, count(distinct(outlet_org_master.org_id_n)) as sso3_count_n from (select source_id_n as source_id_n, round((sum(dimension_1_n)/100),0) as injection_qty_n from kpi.tr_daily_serial_injection_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 11 and actor_type_n = 2 group by source_id_n having round((sum(dimension_1_n)/100),0) >= (select property_value_n from kpi.ms_property_master where property_key_v = 'stable_sso_injection_qty') ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.source_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by cso_org_links.node_id_n order by cso_org_links.node_id_n;

--(3) DAILY SSO:
select daily_injection_aggr.entity_id_n as node_id_n, round((sum(daily_injection_aggr.daily_sso_outlets_n)/(extract(day from now())::numeric)),0) as daily_sso_n from (select daily_event_aggr.day_id_n as day_id_n, cso_org_links.node_id_n as entity_id_n, count(distinct(outlet_org_master.org_id_n)) as daily_sso_outlets_n from (select day_id_n as day_id_n, source_id_n as source_id_n from kpi.tr_daily_serial_injection_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 11 and actor_type_n = 2 group by day_id_n, source_id_n ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.source_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by day_id_n, entity_id_n ) as daily_injection_aggr group by daily_injection_aggr.entity_id_n order by daily_injection_aggr.entity_id_n;

--(4) URO:
select cso_org_links.node_id_n as node_id_n, count(distinct(outlet_org_master.org_id_n)) as uro_count_n from (select actor_id_n as actor_id_n, sum(dimension_2_n) as revenue_value_n from kpi.tr_daily_mobo_transaction_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 21 and actor_type_n = 1 and source_id_n = 0 and instance_type_n = 33 and instance_id_n in (select metrics_id_n from kpi.ms_metrics_master where metrics_type_n = 33 and metrics_name_v in ('Purchase Data Package', 'Indosat Reload')) group by actor_id_n ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.actor_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by cso_org_links.node_id_n order by cso_org_links.node_id_n;

--(5) URO 20K+
select cso_org_links.node_id_n as node_id_n, count(distinct(outlet_org_master.org_id_n)) as uro20_count_n from (select actor_id_n as actor_id_n, sum(dimension_2_n) as revenue_value_n from kpi.tr_daily_mobo_transaction_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 21 and actor_type_n = 1 and source_id_n = 0 and instance_type_n = 33 and instance_id_n in (select metrics_id_n from kpi.ms_metrics_master where metrics_type_n = 33 and metrics_name_v in ('Purchase Data Package', 'Indosat Reload')) group by actor_id_n having round((sum(dimension_2_n)/100),2) >= (select property_value_n from kpi.ms_property_master where property_key_v = 'revenue_transaction_value') ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.actor_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by cso_org_links.node_id_n order by cso_org_links.node_id_n;

--(6) DAILY URO:
select daily_uro_aggr.node_id_n as node_id_n, round((sum(daily_uro_outlets_n)/(extract(day from now())::numeric)),0) as daily_uro_n from (select daily_event_aggr.day_id_n as day_id_n, cso_org_links.node_id_n as node_id_n, count(distinct(outlet_org_master.org_id_n)) as daily_uro_outlets_n from (select day_id_n as day_id_n, actor_id_n as actor_id_n from kpi.tr_daily_mobo_transaction_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and metrics_type_n = 21 and actor_type_n = 1 and source_id_n = 0 and instance_type_n = 33 and instance_id_n in (select metrics_id_n from kpi.ms_metrics_master where metrics_type_n = 33 and metrics_name_v in ('Purchase Data Package', 'Indosat Reload')) group by day_id_n, actor_id_n ) as daily_event_aggr inner join kpi.ms_report_org_master as outlet_org_master on (outlet_org_master.org_type_n = 6 and outlet_org_master.aggregation_id_n = daily_event_aggr.actor_id_n) inner join kpi.ms_user_org_links as cso_org_links on (cso_org_links.dest_org_id_n = outlet_org_master.org_id_n and cso_org_links.status_n = 174 and 1031 = any(cso_org_links.position_id_n)) group by day_id_n, node_id_n ) as daily_uro_aggr group by daily_uro_aggr.node_id_n order by daily_uro_aggr.node_id_n;

--(7) MOBO Sell-In >= 50K:
select cso_node_master.node_id_n, sum(mobo_summary_aggr.mobo_high_n) as mobo_sellin_count_n from (select node_id_n as node_id_n, sum(mobo_high_n) as mobo_high_n from kpi.tr_mobo_summary_aggr where month_id_n = case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymm')::numeric else to_char((date_trunc('month', current_date - interval '1 month'))::date,'yyyymm')::numeric end group by node_id_n ) as mobo_summary_aggr inner join kpi.ms_report_node_master as cso_node_master on (cso_node_master.node_id_n = mobo_summary_aggr.node_id_n) group by cso_node_master.node_id_n order by cso_node_master.node_id_n;

