-- MPC DUMP QUERIES:
--(1) Starter Pack: (Stock Entry)
select mpc_node_master.org_id_n, mpc_node_master.org_short_code_v, round((sum(daily_event_aggr.dimension_1_n)/100),0) as starter_pack_count from (select actor_id_n as actor_id_n, source_id_n as source_id_n, sum(dimension_1_n) as dimension_1_n from kpi.tr_daily_event_metrics_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and event_type_n = 1 and metrics_type_n = 11 and metrics_id_n in (select metrics_id_n from kpi.ms_metrics_master where ext_metrics_id_v in (select unnest(string_to_array(property_value_v::text, ','::text)::character varying[]) from kpi.ms_property_master where property_key_v ilike 'starter_pack_master')) and actor_type_n = 2 group by actor_id_n, source_id_n )as daily_event_aggr inner join kpi.ms_report_node_master as mpc_node_master on (mpc_node_master.org_type_n = 7 and 1039 = any(mpc_node_master.position_id_n) and mpc_node_master.aggregation_id_n = daily_event_aggr.actor_id_n and mpc_node_master.org_aggr_id_n != daily_event_aggr.source_id_n) group by mpc_node_master.org_id_n, mpc_node_master.org_short_code_v order by mpc_node_master.org_id_n;

--(2) Voucher: (Stock Entry)
select mpc_node_master.org_id_n, mpc_node_master.org_short_code_v, round((sum(daily_event_aggr.dimension_1_n)/100),0) as voucher_count from (select actor_id_n as actor_id_n, source_id_n as source_id_n, sum(dimension_1_n) as dimension_1_n from kpi.tr_daily_event_metrics_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and event_type_n = 1 and metrics_type_n = 11 and metrics_id_n in (select metrics_id_n from kpi.ms_metrics_master where ext_metrics_id_v in (select unnest(string_to_array(property_value_v::text, ','::text)::character varying[]) from kpi.ms_property_master where property_key_v ilike 'voucher_master')) and actor_type_n = 2 group by actor_id_n, source_id_n )as daily_event_aggr inner join kpi.ms_report_node_master as mpc_node_master on (mpc_node_master.org_type_n = 7 and 1039 = any(mpc_node_master.position_id_n) and mpc_node_master.aggregation_id_n = daily_event_aggr.actor_id_n and mpc_node_master.org_aggr_id_n != daily_event_aggr.source_id_n) group by mpc_node_master.org_id_n, mpc_node_master.org_short_code_v order by mpc_node_master.org_id_n;

--(3) MOBO Balance: (Indosat To Org Transfer)
select mpc_org_master.org_id_n, mpc_org_master.org_short_code_v, round((sum(daily_event_aggr.dimension_1_n)/100),0) as mobo_balance from (select actor_id_n as actor_id_n, sum(dimension_1_n) as dimension_1_n from kpi.tr_daily_indosat_transfer_aggr where day_id_n between case when (extract(day from now())::numeric != 1) then to_char((date_trunc('month', current_date))::date,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 mon'::interval)::date,'yyyymmdd')::numeric end and case when (extract(day from now())::numeric != 1) then to_char(now() -'1 day'::interval,'yyyymmdd')::numeric else to_char((date_trunc('month', current_date) - '1 day'::interval)::date,'yyyymmdd')::numeric end and actor_type_n = 1 group by actor_id_n ) as daily_event_aggr inner join kpi.ms_report_org_master as mpc_org_master on (mpc_org_master.org_type_n = 7 and mpc_org_master.aggregation_id_n = daily_event_aggr.actor_id_n) group by mpc_org_master.org_id_n, mpc_org_master.org_short_code_v order by mpc_org_master.org_id_n;


