DELETE FROM INTERFACE.MS_INTERFACE_ATTR WHERE NAME_V = 'Cleanup Conf';
DROP TABLE INTERFACE.TR_CLEAN_UP_SUMMARY CASCADE;
DROP SEQUENCE  INTERFACE.TR_CLEAN_UP_SUMMARY_SEQ CASCADE;

CREATE SEQUENCE INTERFACE.TR_CLEAN_UP_SUMMARY_SEQ INCREMENT 1 START 10001 MINVALUE 1 CACHE 1;

-- TR_CLEAN_UP_SUMMARY

CREATE TABLE INTERFACE.TR_CLEAN_UP_SUMMARY
(
    CLEANUP_ID_N 				NUMERIC(19,0) NOT NULL DEFAULT NEXTVAL('INTERFACE.TR_CLEAN_UP_SUMMARY_SEQ'::REGCLASS),
	INTERFACE_ID_N				NUMERIC(19,0) NOT NULL,
	USER_ID_V					CHARACTER VARYING(20) NOT NULL,
	ACTVITY_NAME_V				CHARACTER VARYING(200) NOT NULL,
	MESSAGE_V					CHARACTER VARYING(200),
	STATUS_N					NUMERIC(19,0) NOT NULL,
	INITIATED_DATE_DT			DATE NOT NULL,
	LAST_UPDATED_TIME_DT		TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	CONSTRAINT TR_CLEAN_UP_SUMMARY_PK PRIMARY KEY (CLEANUP_ID_N),
	CONSTRAINT TR_CLEAN_UP_SUMMARY_FK FOREIGN KEY(INTERFACE_ID_N) REFERENCES INTERFACE.MS_INTERFACE (INTERFACE_ID_N),
	CONSTRAINT TR_CLEAN_UP_SUMMARY_UK UNIQUE (INTERFACE_ID_N, INITIATED_DATE_DT)
);


INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1064045, 1064, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1065044, 1065, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1066043, 1066, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1067044, 1067, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1068045, 1068, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1069045, 1069, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1070045, 1070, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1071042, 1071, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1075046, 1075, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1076045, 1076, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1077045, 1077, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1078046, 1078, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1079045, 1079, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1080046, 1080, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1081042, 1081, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1082044, 1082, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1138039, 1138, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1143039, 1143, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1153040, 1153, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1165639, 1165, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1166040, 1166, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1167040, 1167, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1168040, 1168, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1169040, 1169, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1170040, 1170, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1171040, 1171, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1172040, 1172, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1173040, 1173, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1174040, 1174, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1175040, 1175, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1176040, 1176, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1177040, 1177, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1178040, 1178, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1179040, 1179, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1180040, 1180, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1181040, 1181, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1182040, 1182, 'Cleanup Conf', '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}', now());


update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1064045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1065044;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1066043;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1067044;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1068045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1069045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1070045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1071042;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1075046;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1076045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1077045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1078046;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1079045;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1080046;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1081042;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1082044;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1138039;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1143039;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1153040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1165639;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1166040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1167040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1168040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1169040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1170040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1171040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1172040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1173040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1174040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1175040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1176040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1177040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1178040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1179040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1180040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1181040;
update interface.ms_interface_attr set value_v = '{"1001":{"cleanup-tables":{"temporary":true,"validation":true,"failure":false,"summary":false},"retension":100},"1002":{"cleanup-tables":{"temporary":true,"validation":true,"failure":true,"summary":true},"retension":100},"default":"1001","is-enabled":true}' where attribute_id_n = 1182040;


select * from interface.ms_interface_attr where name_v = 'Cleanup Conf' order by 1;
--select max(attribute_id_n) from interface.ms_interface_attr where interface_id_n in (select interface_id_n from interface.ms_interface_attr where name_v = 'Field Lookup Conf'  order by 1) group by interface_id_n order by 1;
