UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{"process_enabled":true, "fields":{"actor_field":"Credit Party ID", "metric_field":"Account Type", "source_field":"Organization ID", "instance_field":"Transaction Channel"}, "error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"}, "table_name":"tr_temp_upload_metrics_revenue_aggr", "lookup_query":"select * from kpi.update_aggregate_lookup_revenue_master(?, ?);","notexist-lookup-flag":true,"daily_table":"tr_daily_org_transfer_aggr","monthly_table":"tr_monthly_org_transfer_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1"duplicate_val1064040ation_conf":{"schema_name":"kpi","table_name":"tr_temp_org_to_org_val1064040ation","field_indexes":[1]}}' WHERE ATTRIBUTE_ID_N = 1064040;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{"process_enabled":true,"fields":{"actor_field":"Organization ID","metric_field":"Initiator Type","source_field":"SP Operator ID","instance_field":""}, "error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301", "instance_field":"60401"}, "table_name":"tr_temp_upload_metrics_revenue_aggr","lookup_query":"select * from kpi.update_aggregate_lookup_revenue_master(?, ?);","notexist-lookup-flag":true,"daily_table":"tr_daily_indosat_transfer_aggr","monthly_table":"tr_monthly_indosat_transfer_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1,"duplicate_val1065039ation_conf":{"schema_name":"kpi","table_name":"tr_temp_indosat_to_org_val1065039ation","field_indexes":[3]}}' WHERE ATTRIBUTE_ID_N = 1065039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{"process_enabled":true,"fields":{"actor_field":"Organization Shortcode","metric_field":"Transaction Type","source_field":"Organization Shortcode","instance_field":""},"error_codes":{"metric_field":"60201","instance_field":"60401","actor_field":"60101","source_field":"60301"},"table_name":"tr_temp_upload_metrics_revenue_aggr","lookup_query":"select * from kpi.update_aggregate_lookup_revenue_master(?, ?);","notexist-lookup-flag":true,"daily_table":"tr_daily_sale_revenue_org_aggr","monthly_table":"tr_monthly_sale_revenue_org_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1}' WHERE ATTRIBUTE_ID_N = 1067039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "CI ID", "metric_field": "Packet data name", "source_field": "Org Id", "instance_field": "System source" }, "error_codes": { "actor_field": "60102", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "lacci_mapping": { "CI ID": "LAC ID~CI ID" }, "reprocess": { "event_type": 104, "error_code": 60102 }, "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "daily_table": "tr_daily_package_act_seller_aggr", "monthly_table": "tr_monthly_package_act_seller_aggr" }' WHERE ATTRIBUTE_ID_N = 1068039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "CI ID", "metric_field": "Packet data name", "source_field": "Org Id", "instance_field": "System source" }, "error_codes": { "actor_field": "60102", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lacci_mapping": { "CI ID": "LAC ID~CI ID" }, "reprocess": { "event_type": 105, "error_code": 60102 }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_package_act_buyer_aggr", "monthly_table": "tr_monthly_package_act_buyer_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1069039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "CI ID", "metric_field": { "39": "Unit of Measure", "37": "Revenue type" }, "source_field": "Org Id", "instance_field": "Revenue category" }, "error_codes": { "actor_field": "60102", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lacci_mapping": { "CI ID": "LAC ID~CI ID" }, "reprocess": { "event_type": 106, "error_code": 60102 }, "table_name": "tr_temp_upload_metrics_revenue_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_revenue_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_usage_metrics_aggr", "monthly_table": "tr_monthly_usage_metrics_aggr", "no_of_join_query_params": 2, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1070039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "SMORGShortcode", "metric_field": { "43": "TransactionType,ProductName", "46": "TransactionType,ProductGroup" }, "source_field": "SMORGShortcode", "instance_field": "TransactionType" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_upload_metrics_trans_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_trans_master(?, ?);", "notexist-lookup-flag": true, "default_conf": { "field": "ProductGroup", "default_value": "Default Package Type" }, "metric_delimiter": "\|", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "cs_daily_table": "tr_daily_mobo_crosselling_aggr", "cs_monthly_table": "tr_monthly_mobo_crosselling_aggr", "daily_table": "tr_daily_mobo_transaction_aggr", "monthly_table": "tr_monthly_mobo_transaction_aggr", "cross_sell_lacci_config": { "B#CIID": "B#LACID~B#CIID", "A#CIID": "A#LACID~A#CIID" }, "data_filter": [ { "operation": "in", "values": [ "Purchase Data Package", "Indosat Reload", "Voucher card injection" ], "field_index": 2 } ] }' WHERE ATTRIBUTE_ID_N = 1075040;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "CI ID", "metric_field": "Product Value", "source_field": "Org Id", "instance_field": "Reload system" }, "error_codes": { "actor_field": "60102", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lacci_mapping": { "CI ID": "LAC ID~CI ID" }, "reprocess": { "event_type": 107, "error_code": 60102 }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_reload_seller_aggr", "monthly_table": "tr_monthly_reload_seller_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1076039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "CI ID", "metric_field": "Product Value", "source_field": "", "instance_field": "Reload system" }, "error_codes": { "actor_field": "60102", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lacci_mapping": { "CI ID": "LAC ID~CI ID" }, "reprocess": { "event_type": 108, "error_code": 60102 }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_reload_buyer_aggr", "monthly_table": "tr_monthly_reload_buyer_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1077039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "B#MSISDN", "metric_field": "B#MSISDN", "source_field": "OperatorID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_usage_customer_aggr", "monthly_table": "tr_monthly_usage_customer_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1078041;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "B#MSISDN", "metric_field": "PACKAGE_NAME", "source_field": "OperatorID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_addon_customer_aggr", "monthly_table": "tr_monthly_addon_customer_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1079040;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "B#MSISDN", "metric_field": "B#MSISDN", "source_field": "OperatorID", "instance_field": "" }, "error_codes": { "metric_field": "60201", "instance_field": "60401", "actor_field": "60101", "source_field": "60301" }, "table_name": "tr_temp_upload_metrics_aggr", "lookup_query": "select * from kpi.update_aggregate_lookup_master(?, ?);", "notexist-lookup-flag": true, "daily_table": "tr_daily_reload_customer_aggr", "monthly_table": "tr_monthly_reload_customer_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1080041;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "Organization ID", "metric_field": "Account Type", "source_field": "Organization ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lookup_query": "select * from kpi.update_aggregate_lookup_orgbal_master(?, ?);", "notexist-lookup-flag": true, "table_name": "tr_temp_upload_metrics_orgbal_aggr", "daily_table": "tr_daily_org_balance_aggr", "monthly_table": "tr_monthly_org_balance_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1 }' WHERE ATTRIBUTE_ID_N = 1082039;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": { "10": "ID_OUTLET", "13": "MICRO" }, "metric_field": "", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "lookup_query": "", "notexist-lookup-flag": true, "table_name": "tr_temp_daily_sso_aggr", "daily_table": "tr_daily_daily_sso_aggr", "monthly_table": "tr_monthly_daily_sso_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 2, "no_of_monthly_join_queries": 2, "data_filter": [], "duplicate_val1168037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1168037ate_daily_sso_aggr", "field_indexes": [ 0, 1, 2, 3 ] } }' WHERE ATTRIBUTE_ID_N = 1168037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": { "10": "ID_OUTLET", "13": "MICRO" }, "metric_field": "FLAG_ACM", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_rguga_injection_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_rguga_injection_aggr", "monthly_table": "tr_monthly_rguga_injection_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 2, "no_of_monthly_join_queries": 2, "data_filter": [ { "operation": "in", "values": [ "INJECTED", "Injected", "injected" ], "field_index": 4 } ], "duplicate_val1169037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1169037ate_rguga_injection_aggr", "field_indexes": [ 0, 1, 2, 3, 4, 5 ] } }' WHERE ATTRIBUTE_ID_N = 1169037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": { "10": "OUTLET", "13": "MICRO" }, "metric_field": "", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_tertiary_sales_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_tertiary_sales_aggr", "monthly_table": "tr_monthly_tertiary_sales_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 2, "no_of_monthly_join_queries": 2, "data_filter": [], "duplicate_val1170037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1170037ate_tertiary_sales_aggr", "field_indexes": [ 0, 1, 2, 3 ] } }' WHERE ATTRIBUTE_ID_N = 1170037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "MICRO", "metric_field": "REVENUE_TYPE", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_total_usage_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_total_usage_aggr", "monthly_table": "tr_monthly_total_usage_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "data_filter": [], "duplicate_val1172037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1172037ate_total_usage_aggr", "field_indexes": [ 0, 1, 2, 3 ] } }' WHERE ATTRIBUTE_ID_N = 1172037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "MICRO", "metric_field": "", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_mobo_usage_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_mobo_usage_aggr", "monthly_table": "tr_monthly_mobo_usage_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "data_filter": [], "duplicate_val1173037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1173037ate_usage_revenue_aggr", "field_indexes": [ 0, 1, 2 ] } }' WHERE ATTRIBUTE_ID_N = 1173037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "MICRO", "metric_field": "", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_total_rguga_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_total_rguga_aggr", "monthly_table": "tr_monthly_total_rguga_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "data_filter": [], "duplicate_val1174037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1174037ate_total_rguga_aggr", "field_indexes": [ 0, 1, 2 ] } }' WHERE ATTRIBUTE_ID_N = 1174037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "MICRO", "metric_field": "CATEGORY", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_low_revenue_site_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_low_revenue_site_aggr", "monthly_table": "tr_monthly_low_revenue_site_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "data_filter": [], "duplicate_val1175037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1175037ate_low_revenue_site_aggr", "field_indexes": [ 0, 1, 2, 3 ] } }' WHERE ATTRIBUTE_ID_N = 1175037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": "MICRO", "metric_field": "", "source_field": "SITE", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_site_rguga_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_site_rguga_aggr", "monthly_table": "tr_monthly_site_rguga_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 1, "no_of_monthly_join_queries": 1, "data_filter": [], "duplicate_val1176037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1176037ate_site_rguga_aggr", "field_indexes": [ 0, 1, 2 ] } }' WHERE ATTRIBUTE_ID_N = 1176037;

UPDATE INTERFACE.MS_INTERFACE_ATTR SET VALUE_V = '{ "process_enabled": true, "fields": { "actor_field": { "10": "OUTLET", "13": "MICRO" }, "metric_field": "", "source_field": "SITE_ID", "instance_field": "" }, "error_codes": { "actor_field": "60101", "metric_field": "60201", "source_field": "60301", "instance_field": "60401" }, "table_name": "tr_temp_uro_20k_aggr", "lookup_query": "", "notexist-lookup-flag": true, "daily_table": "tr_daily_uro_20k_aggr", "monthly_table": "tr_monthly_uro_20k_aggr", "no_of_join_query_params": 1, "no_of_daily_join_queries": 2, "no_of_monthly_join_queries": 2, "data_filter": [], "duplicate_val1181037ation_conf": { "schema_name": "kpi", "table_name": "tr_val1181037ate_uro_20k_aggr", "field_indexes": [ 0, 1, 2, 3 ] } }' WHERE ATTRIBUTE_ID_N = 1181037;
