-- To update actor type & lookup configuration for site:(Gopinath)
delete from kpi.ms_actor_lookup_master where actor_type_n in (12,13);
delete from kpi.ms_actor_type_master where actor_type_n in (12,13);

insert into kpi.ms_actor_type_master(actor_type_n, actor_type_name_v, description_v, system_type_v) values (12,'Site Master', 'Site Lookup', 'Internal');
insert into kpi.ms_actor_type_master(actor_type_n, actor_type_name_v, description_v, system_type_v) values (13,'Operator Node Master', 'Operator Node Lookup', 'Internal');

insert into kpi.ms_actor_lookup_master(actor_type_n, reference_path_v, input_type_v, input_column_v, output_type_v, output_column_v, reference_type_n) values (12,'select ? as actor_id_n from kpi.ms_lookup_master where ?', 'string', 'ext_ref_code_v', 'numeric', 'aggregation_id_n', null);
insert into kpi.ms_actor_lookup_master(actor_type_n, reference_path_v, input_type_v, input_column_v, output_type_v, output_column_v, reference_type_n) values (13,'select ? as actor_id_n from kpi.ms_report_user_master where ?', 'string', 'operator_id_v', 'numeric', 'node_aggr_id_n', 2);

-- To configure new metrics for interface hadoop file feeds:(Gopinath)
delete from kpi.ms_metrics_master where metrics_id_n in (111,112,113);
insert into kpi.ms_metrics_master(metrics_id_n, metrics_name_v, description_v, metrics_type_n, ext_reference_id_v, definition_v, derived_mode_v) values (111, 'MOBO Transfer', 'MOBO Transfer', 21, 'MOBO Transfer', 'Aggregated', null);
insert into kpi.ms_metrics_master(metrics_id_n, metrics_name_v, description_v, metrics_type_n, ext_reference_id_v, definition_v, derived_mode_v) values (112, 'RGU-GA Injection', 'RGU-GA Injection', 21, 'RGU-GA Injection', 'Aggregated', null);
insert into kpi.ms_metrics_master(metrics_id_n, metrics_name_v, description_v, metrics_type_n, ext_reference_id_v, definition_v, derived_mode_v) values (113, 'Daily SSO', 'Daily SSO', 21, 'Daily SSO', 'Aggregated', null);

-- INTERFACE.MS_MODULE:
insert into interface.ms_module(module_id_n, name_v, call_back_v, description_v) values (232, 'INTDW024 - Secondary MOBO', null , 'Incoming Secondary MOBO File from DWH');
insert into interface.ms_module(module_id_n, name_v, call_back_v, description_v) values (243, 'INTDW027 - MOBII RGU-GA Injection', null , 'Incoming MOBII RGU-GA Injection File from DWH');
insert into interface.ms_module(module_id_n, name_v, call_back_v, description_v) values (244, 'INTDW033 - MOBII Daily SSO', null , 'Incoming MOBII Daily SSO File from DWH');

-- INTERFACE.MS_INTERFACE:
insert into interface.ms_interface (interface_id_n, name_v, module_id_n, interface_type_n, trans_type_n, seq_n, converter_v, publisher_v, response_processor_v, last_updated_time_dt) values (1153, 'INTDW024 - Secondary MOBO', 232, 2, 2, 1, 'java:global/EnhancesysManagement/IntegrationServices/CSVtoJSONConverter!com.enhancesys.integration.services.interfaces.converter.DataConverter', 'java:global/EnhancesysManagement/IntegrationPublishers/WebServicePublisher!com.enhancesys.integration.services.interfaces.publisher.DataPublisher', NULL, now());
insert into interface.ms_interface (interface_id_n, name_v, module_id_n, interface_type_n, trans_type_n, seq_n, converter_v, publisher_v, response_processor_v, last_updated_time_dt) values (1165, 'INTDW027 - MOBII RGU-GA Injection', 243, 2, 2, 1, 'java:global/EnhancesysManagement/IntegrationServices/CSVtoJSONConverter!com.enhancesys.integration.services.interfaces.converter.DataConverter', 'java:global/EnhancesysManagement/IntegrationPublishers/WebServicePublisher!com.enhancesys.integration.services.interfaces.publisher.DataPublisher', NULL, now());
insert into interface.ms_interface (interface_id_n, name_v, module_id_n, interface_type_n, trans_type_n, seq_n, converter_v, publisher_v, response_processor_v, last_updated_time_dt) values (1166, 'INTDW033 - MOBII Daily SSO', 244, 2, 2, 1, 'java:global/EnhancesysManagement/IntegrationServices/CSVtoJSONConverter!com.enhancesys.integration.services.interfaces.converter.DataConverter', 'java:global/EnhancesysManagement/IntegrationPublishers/WebServicePublisher!com.enhancesys.integration.services.interfaces.publisher.DataPublisher', NULL, now());

-- Attributes for interface 1153 (INTDW024 - Secondary MOBO - Receive file)
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153001, 1153, 'Remote Host', 'REMOTE_HOST', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153002, 1153, 'Remote Port', 'REMOTE_PORT', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153003, 1153, 'Remote User', 'REMOTE_USER', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153004, 1153, 'Remote Password', 'REMOTE_PWD', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153005, 1153, 'Remote File', 'secondary_mobo_bi', now());                                 
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153006, 1153, 'Remote FileName Format', 'yyyyMMdd', now());                    
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153007, 1153, 'Remote File Format', 'csv', now());                                   
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153008, 1153, 'Control file format', 'ctl', now());                                  
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153009, 1153, 'Remote Dir', '/home/appuser/interfaces/DWH/master_files/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153010, 1153, 'Remote control directory', '/home/appuser/interfaces/DWH/master_files/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153011, 1153, 'Remote rejected directory', '/home/appuser/interfaces/DWH/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153012, 1153, 'Remote rejected control directory', '/home/appuser/interfaces/DWH/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153013, 1153, 'Remote backup directory', '/home/appuser/interfaces/DWH/backup/master_files/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153014, 1153, 'Remote Control Backup Directory', '/home/appuser/interfaces/DWH/backup/master_files/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153015, 1153, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153016, 1153, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153017, 1153, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153018, 1153, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153019, 1153, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153020, 1153, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153021, 1153, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153022, 1153, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153023, 1153, 'Local Filter Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/filter_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153024, 1153, 'Local Filter Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/filter_file/secondary_mobo_bi/', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153025, 1153, 'Received File Type', 'Request File Type', now());                     
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153026, 1153, 'Csv Delimeter', '\|', now());                                         
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153027, 1153, 'Rejection File Headers', 'MPC_CODE|DATE|ORGANIZATION_ID|DEALER_MSISDN|AMOUNT|ERRORCODE|ERRORMESSAGE', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153028, 1153, 'Rejection File Preparation Class', 'java:global/EnhancesysManagement/IntegrationServices/DWHRejectionFilePreparation!com.enhancesys.integration.services.interfaces.rejection.RejectionFilePreparation', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153029, 1153, 'Client Id', '0', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153030, 1153, 'Is Sftp', 'true', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153031, 1153, 'File Headers', 'MPC_CODE|DATE|ORGANIZATION_ID|DEALER_MSISDN|AMOUNT', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153032, 1153, 'Field Validation Conf', 'MPC_CODE;M;R;[a-zA-Z0-9]+%DATE;M;RD;[0-9]{8};yyyyMMdd%ORGANIZATION_ID;M;R;[0-9]+%DEALER_MSISDN;M;R;[0-9]+%AMOUNT;M;R;^-?([0-9]\d*(\.\d+)?)$', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153033, 1153, 'CSV MERGER', 'java:global/EnhancesysManagement/IntegrationServices/GenericFileProcessor!com.enhancesys.integration.services.interfaces.merger.CSVMerger', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153034, 1153, 'Validation Conf Delimiter', '%', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153035, 1153, 'File Data Batch Size', '5000', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153036, 1153, 'Rejection File Query', 'select data_string_v, error_code, error_message from kpi.tr_temp_upload_aggr_failure where file_id_n = ?', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153037, 1153, 'Field Lookup Conf', '{"process_enabled":true,"fields":{"actor_field":"ORGANIZATION_ID","metric_field":"ORGANIZATION_ID","source_field":"MPC_CODE","instance_field":""},"error_codes":{"actor_field":"60101","metric_field":"60201","source_field":"60301","instance_field":"60401"},"table_name":"tr_temp_upload_metrics_aggr","lookup_query":"","notexist_lookup":"","no_of_params":{},"daily_table":"tr_daily_secondary_mobo_aggr","monthly_table":"tr_monthly_secondary_mobo_aggr","no_of_join_query_params":1,"no_of_daily_join_queries":1,"no_of_monthly_join_queries":1}', now());
insert into interface.ms_interface_attr (attribute_id_n, interface_id_n, name_v, value_v, last_updated_time_dt) values (1153038, 1153, 'Incoming File Records Limit', '', now());

-- Email Notification Attributes for interface -->INTDW024 - Secondary MOBO
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053001, 1153, 'FILE_REJECTED_CTL_0', 'email', 'int_md5_hash_key_failed', 'FILE REJECTED - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053002, 1153, 'FILE_NOT_FOUND_0', 'email', 'int_file_not_found', 'FILE NOT FOUND - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053003, 1153, 'FILE_REJECTED_PART_0', 'email', 'int_file_rejected_partially', 'FILE REJECTED PARTIALLY - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053004, 1153, 'FILE_REJECTED_FULL_0', 'email', 'int_file_rejected_fully', 'FILE REJECTED FULLY - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053005, 1153, 'FILE_SUCCESS_0', 'email', 'int_file_processed_sucessfully', 'FILE SUCCESSFULLY PROCESSED - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 2, now(),'en');
insert into interface.ms_interface_notification (interface_notification_id_n, interface_id_n, scenario_v, media_v, template_name_v, subject_v, to_first_name_v, to_address_v, to_cc_v, to_bcc_v, status_n, last_updated_time_dt,language_v) values (1053006, 1153, 'CONNECTION_REFUSED_0', 'email', 'int_connection_refused', 'CONNECTION REFUSED - INTDW024 - Secondary MOBO', 'Support Team', '', '', '', 1, now(),'en');

