
INSERT INTO INTERFACE.MS_MODULE(MODULE_ID_N, NAME_V, CALL_BACK_V, DESCRIPTION_V) VALUES  (235, 'DAILY_DUMP - Outlet Sales', null , '');


INSERT INTO INTERFACE.MS_INTERFACE (INTERFACE_ID_N, NAME_V, MODULE_ID_N, INTERFACE_TYPE_N, TRANS_TYPE_N, SEQ_N, CONVERTER_V, PUBLISHER_V, RESPONSE_PROCESSOR_V, LAST_UPDATED_TIME_DT) VALUES (1156, 'DAILY_DUMP - Outlet Sales', 235	, 2, 1, 1, 'java:global/EnhancesysManagement/IntegrationServices/GenericDataProcessor!com.enhancesys.integration.services.interfaces.processor.PullFromMongo', '', NULL, now());



--Attributes for interface 1156 (DAILY_DUMP - Outlet Sales)
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156001, 1156, 'Remote Host', '192.168.2.251', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156002, 1156, 'Remote Port', '22', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156003, 1156, 'Remote User', 'appuser', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156004, 1156, 'Remote Password', 'app@123', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156005, 1156, 'Remote File', 'Outlet_Sales', now());                                                                             
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156006, 1156, 'Remote FileName Format', 'yyyyMMdd', now());                                                                          
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156007, 1156, 'Remote File Format', 'csv', now());                                                                                         
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156008, 1156, 'Control file format', 'ctl', now());                                                                                        
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156009, 1156, 'Remote Dir', '/home/appuser/interfaces/DAILY_DUMPS/master_files/outlet_sales/', now());                 
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156010, 1156, 'Remote control directory', '/home/appuser/interfaces/DAILY_DUMPS/master_files/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156011, 1156, 'Remote rejected directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156012, 1156, 'Remote rejected control directory', '/home/appuser/interfaces/DAILY_DUMPS/rejected_file/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156013, 1156, 'Remote backup directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156014, 1156, 'Remote Control Backup Directory', '/home/appuser/interfaces/DAILY_DUMPS/backup/master_files/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156015, 1156, 'Local Dir', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156016, 1156, 'Local control directory', '/snoc/interfaces/S-NOC/interfaces/master_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156017, 1156, 'Local backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156018, 1156, 'Local Control Backup Directory', '/snoc/interfaces/S-NOC/interfaces/backup/master_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156019, 1156, 'Local rejected directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156020, 1156, 'Local rejected control directory', '/snoc/interfaces/S-NOC/interfaces/rejected_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156021, 1156, 'Local rejected backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156022, 1156, 'Local rejected control backup directory', '/snoc/interfaces/S-NOC/interfaces/backup/rejected_file/daily_dumps/outlet_sales/', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156023, 1156, 'Received File Type', 'Request File Type', now());                                                                           
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156024, 1156, 'Csv Delimeter', '|', now());                                                                                               
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156025, 1156, 'File Headers', 'Date|Region|HOR Name|Area|HOS Name|Sales Area|SAM Name|CSM Name|CSO Name|Outlet Ref Id|Outlet name|Contact number|Mobo number|Starter pack Count|Voucher Count|MOBO Sellin Value (Using MOBII)|ACT 1 MSISDN Count|GA-FR MSISDN Count|RGU-GA MSISDN Count|MOBO Sellout value|VC Redeem value', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156026, 1156, 'Client Id', '0', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156027, 1156, 'Is Sftp', 'true', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156028, 1156, 'Schema Name', 'daily_dump_snapshot', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156029, 1156, 'Collection Name', 'outlet_hierachy_dump', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156030, 1156, 'Daily Dump Conf', '{"date":"date","region":"region","hor name":"hor_name","area":"area","hos name":"hos_name","sales area":"sales_area","sam name":"sam_name","csm name":"csm_name","cso name":"cso_name","outlet ref id":"outlet_ref_id","outlet name":"outlet_name","contact number":"contact_number","mobo number":"mobo_number","starter pack count":"starter_pack_count","voucher count":"voucher_count","mobo sellin value (using mobii)":"mobo_sellin_value_(using_mobii)","act 1 msisdn count":"act_1_msisdn_count","ga-fr msisdn count":"ga-fr_msisdn_count","rgu-ga msisdn count":"rgu-ga_msisdn_count","mobo sellout value":"mobo_sellout_value","vc redeem value":"vc_redeem_value"}', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156031, 1156, 'Query Field', 'dump_crtd_dt_num', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156032, 1156, 'Date Duration', '1', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156033, 1156, 'Process Name', 'Outlet_Sales', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156034, 1156, 'Mongo Connection Id', 'snoc-r5', now());
INSERT INTO INTERFACE.MS_INTERFACE_ATTR (ATTRIBUTE_ID_N, INTERFACE_ID_N, NAME_V, VALUE_V, LAST_UPDATED_TIME_DT) VALUES (1156035, 1156, 'Processor Url', 'java:global/EnhancesysManagement/IntegrationServices/GenericDailyDump!com.enhancesys.integration.services.interfaces.processor.PullFromMongo', now());

