--Integration TRIGGERS..
--Integration TRIGGERS..
drop extension if exists lo cascade;
create extension lo;
--TR_MODULE_SUMMARY triggers..
CREATE TRIGGER TR_INT_SUM_ORG_REQ_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_SUMMARY FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(ORGNL_REQUEST_DATA_B);
CREATE TRIGGER TR_INT_SUM_REQ_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_SUMMARY FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(REQUEST_DATA_B);
CREATE TRIGGER TR_INT_SUM_ACK_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_SUMMARY FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(ACK_DATA_B);
CREATE TRIGGER TR_INT_SUM_ORG_RES_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_SUMMARY FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(ORGNL_RESPONSE_DATA_B);
CREATE TRIGGER TR_INT_SUM_RES_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_SUMMARY FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(RESPONSE_DATA_B);

--TR_MODULE_FAILURE triggers..
CREATE TRIGGER TR_INT_FAIL_ACK_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_FAILURE FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(ACK_DATA_B);
CREATE TRIGGER TR_INT_FAIL_RES_DATA_TRIG BEFORE UPDATE OR DELETE ON JOBENGINE.TR_MODULE_FAILURE FOR EACH ROW EXECUTE PROCEDURE LO_MANAGE(RESPONSE_DATA_B);
